### ISSUE TITLE
JaCoCo shades ASM making it impossible to update ASM

### ISSUE THREAD

**Issue by garydgregory** [jacoco/jacoco#1742] opened 2024-10-09 17:07 UTC
JaCoCo shades ASM making it impossible to update ASM in a Maven build.

ATM, it is not possible to test on Java 24-EA. If ASM were a dependency, projects could update ASM and move along. Instead, we must wait for a new release of JaCoCo :-(

**Comment by Godin** [comment] 2024-10-09 19:03
Duplicate of #1200 

----

Also let me quote https://www.jacoco.org/jacoco/trunk/doc/faq.html

> ### When will feature X be released?
> **JaCoCo is maintained by volunteers in their free time. Since we cannot guarantee free capacity, we do not commit to particular release dates.** Typically, you can expect a couple of releases every year.
>
> In the [change log](https://www.jacoco.org/jacoco/trunk/doc/changes.html), you can see all features that have been implemented in master branch and will be available with the next release. And in the meantime you can test latest build of master branch ([Maven SNAPSHOT](https://www.jacoco.org/jacoco/trunk/doc/repo.html)) and provide feedback to us.

**Closed by Godin** 2024-10-09 19:03 UTC
Labels: type: bug :bug:

**Comment by Godin** [comment] 2024-10-09 20:03
While

> in the meantime you can test latest build of master branch ([Maven SNAPSHOT](https://www.jacoco.org/jacoco/trunk/doc/repo.html))

according to https://github.com/jacoco/jacoco/pull/1631#issuecomment-2403297952 I doubt that you need it.
Moreover as long as your application does not contain Java 24 bytecode, JaCoCo 0.8.12 should perfectly work for it even when executed with Java 24.

**Comment by garydgregory** [comment] 2024-10-09 22:28
Hi @Godin 

Please see https://github.com/jacoco/jacoco/pull/1631#issuecomment-2403535283
