### ISSUE TITLE
Last curly bracket of the method not getting covered

### ISSUE THREAD

**Issue by Animikh-Daripa** [jacoco/jacoco#1233] opened 2021-10-18 16:02 UTC
Hi,

I am using Jacoco version 0.8.7. I am using (mocking) realm database,but the last curly braces is not showing as covered. Screenshot attached. What can be the reason for it?

![JacocoRealmCoverage](https://user-images.githubusercontent.com/25586017/137767111-2a0281db-5f9e-466d-988a-a398d2bfca3c.png)

**Comment by donynuransyah** [comment] 2023-03-14 02:26
its still happen 
<img width="613" alt="image" src="https://user-images.githubusercontent.com/47665987/224876939-9a10bcf2-9073-4b6d-9c3f-ba19339f3abe.png">

**Comment by marchof** [comment] 2023-03-14 06:50
Please provide a reproducer (e.g. small GitHub project) where we can analyze the problem. Thx!

**Comment by leslieli** [comment] 2023-07-27 07:35
I met the same problem. I am using Groovy and EclEmma 3.1.7 which has upgraded JaCoCo to 0.8.10

<img width="1109" alt="image" src="https://github.com/jacoco/jacoco/assets/443366/95c36484-3b0e-4005-aa75-5211541c19d2">

**Comment by marchof** [comment] 2023-07-28 07:13
@leslieli Unfortunatelly we cannot debug screenshots. If you want us to analyze this please provide a minimal reproducer (GitHub project) which we can analyze.

**Comment by leslieli** [comment] 2023-08-02 16:45
Hope this one could help. https://github.com/leslieli/JacocoDebug
cc @marchof

**Comment by Godin** [comment] 2023-08-02 20:07
@leslieli yes, this definitely helps

Execution of

```
git clone https://github.com/leslieli/JacocoDebug.git
cd JacocoDebug
mvn compile
javap -v -p target/classes/com/jacdebuger/util/Utils.class
```

shows that curly brace on line number 6 in

```
package com.jacdebuger.util

class Utils {
    public static add(int a, int b) {
        return a + b
    }
}
```

corresponds to bytecode instructions at offset 54 (`nop` followed by `athrow`)

```
  public static java.lang.Object add(int, int);
    descriptor: (II)Ljava/lang/Object;
    flags: (0x0009) ACC_PUBLIC, ACC_STATIC
    Code:
      stack=3, locals=3, args_size=2
         0: nop
         1: invokestatic  #20                 // Method $getCallSiteArray:()[Lorg/codehaus/groovy/runtime/callsite/CallSite;
         4: astore_2
         5: invokestatic  #38                 // Method org/codehaus/groovy/runtime/BytecodeInterface8.isOrigInt:()Z
         8: ifeq          26
        11: getstatic     #40                 // Field __$stMC:Z
        14: ifne          26
        17: invokestatic  #43                 // Method org/codehaus/groovy/runtime/BytecodeInterface8.disabledStandardMetaClass:()Z
        20: ifne          26
        23: goto          47
        26: aload_2
        27: ldc           #44                 // int 0
        29: aaload
        30: iload_0
        31: invokestatic  #50                 // Method java/lang/Integer.valueOf:(I)Ljava/lang/Integer;
        34: iload_1
        35: invokestatic  #50                 // Method java/lang/Integer.valueOf:(I)Ljava/lang/Integer;
        38: invokeinterface #56,  3           // InterfaceMethod org/codehaus/groovy/runtime/callsite/CallSite.call:(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
        43: areturn
        44: nop
        45: nop
        46: athrow
        47: iload_0
        48: iload_1
        49: iadd
        50: invokestatic  #50                 // Method java/lang/Integer.valueOf:(I)Ljava/lang/Integer;
        53: areturn
        54: nop
        55: athrow
      LineNumberTable:
        line 5: 26
        line 6: 44
        line 5: 47
        line 6: 54
        line 6: 54
```

these instructions can not be reached, i.e. Groovy compiler generates dead code, some time ago there was a similar issue https://github.com/jacoco/jacoco/issues/884 with conclusion that such problems should be fixed in Groovy compiler, and according to this previous report they were fixed in Groovy 3.0.7, so there is probably regression on their side - please try 3.0.7 and report this to the developers of Groovy compiler

P.S. also please note that your issue is most likely different from the issue originally reported here, because it was about Kotlin code instead of Groovy :wink:

**Comment by leslieli** [comment] 2023-08-03 00:57
Thanks so much @Godin .

**Comment by gabriel-videla** [comment] 2024-02-14 20:19
> Groovy compiler generates dead code, some time ago there was a similar issue #884 with conclusion that such problems should be fixed in Groovy compiler
> Tried the Groovy 3.0.7, 3.0.8 and 3.0.18, the issue is still there but it disappear at Groovy 4.

@daniellansun, can this be fixed also for Groovy 3? I think the following two changes made in Groovy 4 (related with the ticket https://issues.apache.org/jira/browse/GROOVY-9373) are the ones missing for Groovy 3:

https://github.com/apache/groovy/pull/1443
https://github.com/apache/groovy/pull/1457

**Comment by marchof** [comment] 2024-07-15 20:04
Closing this as in any case this can only be resolved in the Groovy compiler.

**Closed by marchof** 2024-07-15 20:04 UTC
Labels: declined: otherproject :alien:
