### ISSUE TITLE
Incomplete instruction coverage on enum switches

### ISSUE THREAD

**Issue by gallonfizik** [jacoco/jacoco#692] opened 2018-06-07 19:44 UTC
I am an OCD achievement junkie, so I went lengths to to mock default branches on enum switches.
However, instruction coverage is still incomplete.
### Steps to reproduce
Here's a simplest setup:
```java
public class MyEnumWrapper {
    public enum MyEnum {A};

    public static void useEnum(MyEnum arg) {
        switch (arg) {
            case A:
                return;
            default:
                throw new AssertionError();
        }
    }
}

// test
@RunWith(PowerMockRunner.class)
public class MyEnumTest extends PowerMockTestCase {
    @PrepareForTest(MyEnumWrapper.MyEnum.class)
    @Test(expected = AssertionError.class)
    public void throwsAssertionErrorOnDefaultBranch() {
        MyEnumWrapper.MyEnum[] good_values = MyEnumWrapper.MyEnum.values();

        MyEnumWrapper.MyEnum badValue = PowerMockito.mock(MyEnumWrapper.MyEnum.class);
        Whitebox.setInternalState(badValue, "name", "Default");
        Whitebox.setInternalState(badValue, "ordinal", good_values.length);

        MyEnumWrapper.MyEnum[] bad_values = Arrays.copyOf(good_values, good_values.length + 1);
        bad_values[bad_values.length - 1] = badValue;

        PowerMockito.mockStatic(MyEnumWrapper.MyEnum.class);
        PowerMockito.when(MyEnumWrapper.MyEnum.values()).thenReturn(bad_values);
        MyEnumWrapper.useEnum(badValue);
    }
    @Test(expected = NullPointerException.class)
    public void throwsNullPointerException_onNullArgument() {
        Structure.create(null);
    }

    @Test
    public void testUseEnum() {
        MyEnumWrapper.useEnum(MyEnumWrapper.MyEnum.A);
    }

    @Test
    public void dummyRunToCoverConstructor() {
        new MyEnumWrapper();
    }
}
```
JaCoCo version: 0.8.1
Operating system: Win10x64
Tool integration: gradle

### Expected behaviour
100% branch and instruction coverage

### Actual behaviour
100% branch coverage
97% instruction coverage
In the report viewer, the source code view shows all lines green, and switch with a green diamond.
The class/file view however shows incomplete instruction coverage.
![image](https://user-images.githubusercontent.com/23377130/41122417-2d97752c-6aa4-11e8-9486-ad005a2dc1ca.png)
![image](https://user-images.githubusercontent.com/23377130/41122462-4a5b8f7c-6aa4-11e8-81b0-f88f236d13e4.png)

That's somewhat frustrating. Perhaps I'm doing something wrong? Or is there a way to fix this behavior?

**Comment by Godin** [comment] 2018-06-07 19:59
Duplicate of #660

**Closed by Godin** 2018-06-07 19:59 UTC
