### ISSUE TITLE
When using Groovy, methods that return value have incorrect code coverage

### ISSUE THREAD

**Issue by michelzanini** [jacoco/jacoco#892] opened 2019-06-06 17:00 UTC
### Steps to reproduce

JaCoCo version: 0.8.4
Operating system: Mac/OS
Tool integration: Gradle
Spring Boot: 2.1.5.RELEASE
Groovy: 2.5.7
Spock: 1.2-groovy-2.5

### Expected behaviour

When I run tests with Groovy and Spock with the latest versions of Spring Boot / Groovy / Spock and JaCoCo it should correctly identify the lines to cover on method with return value and void methods.

### Actual behaviour

For methods that return a value, JaCoCo thinks there is an additional line at the end of the method and always report it as not covered. 

See screen shot:

![Screen Shot 2019-06-06 at 13 56 44](https://user-images.githubusercontent.com/4479787/59051482-5cb4bf80-8863-11e9-90e8-0ac096eb1bd6.png)

In the screen shot above there should be 4 lines to cover, and they are all covered, my file should have 100% coverage. However, it thinks there are 6 lines. My other files that return values all have the same issue.

Adding the keyword `return` does not do any difference.

**Comment by Godin** [comment] 2019-06-06 17:50
Duplicate of #884

**Closed by Godin** 2019-06-06 17:50 UTC
