### ISSUE TITLE
Filtering options for coverage analysis

### ISSUE THREAD

**Issue by marchof** [jacoco/jacoco#15] opened 2012-08-29 20:30 UTC
JaCoCo should support configurable filtering options for code coverage analysis. This page lists of use cases and requirements: https://github.com/jacoco/jacoco/wiki/FilteringOptions

**Comment by sham-marol** [comment] 2015-01-15 20:12
Hi,

Do we have the filtering option, where I can exclude part of the code in my class example - a method during code coverage analysis. Does the latest release of jacoco has this feature?

**Comment by henri-tremblay** [comment] 2015-02-26 16:06
I understand the goal to have a clean API. But indeed, at some point, something should happen. I had the same issue with my personal projects and have waited too much time.

I used to use Clover, but it was not very stable from one version to another and isn't open source.

Cobertura was too intrusive so I skipped to JaCoCo which I'm happy with.... apart from the filtering. And the only really important filtering seems to be able to tag the code.

I understand that people can then trick JaCoco by using too much tags. But every new tool can be used for evil. Anyway, that's not my use-case. I'm having 100% coverage on EasyMock. So, I want to know when I'm under that mark and easily find the hole. Without filtering, I can't. I need to dig all around the place to find it.

///COVERAGE:OFF from mchr3k is exactly what I would need.

How can I help?  I'm willing to provide a pull request that would be accepted. What would that be?

**Comment by marchof** [comment] 2015-02-26 20:00
@henri-tremblay I agree with you that the API is not the highest priority. Highest priority currently are removing annoying compiler artifacts especially for new Java 7 language constructs. As JaCoCo is fully based on class files source file processing (e.g. for comment parsing) is not in scope.

**Comment by henri-tremblay** [comment] 2015-02-26 20:58
But if the filtering is done by annotations, it won't be really precise. Java 8 will be a bit better since you can put annotations all over the place.

I haven't looked at mchr3k code yet but I would guess the following algorithm:
# Record all coverage
# Grep in the code for tags
# Remove from coverage the code between on an of

It doesn't really require a formal parsing, only a grep. It will be slower then when not activated but if not activated by default it won't matter

WDYT?

**Comment by TomRK1089** [comment] 2015-02-26 21:01
@henri-tremblay My understanding is that there is nothing to grep. JaCoCo analyzes compiled bytecode, not source files. Thus, there will be no magical ///COVERAGE:OFF to find.

**Comment by henri-tremblay** [comment] 2015-02-26 21:22
Hum... I understand. It should still be possible from a Maven task. Another solution would be to have a filter file a bit like FindBugs would do. Since the debug info will provide the line numbers, that should be enough.

**Comment by addedsparkle** [comment] 2015-03-16 09:57
I understand the generated code is causing issues here, and the ability to tag code as excluded from the coverage, but would you consider splitting the filtering of trivial code out into a separate issue that could be merged quicker? It's incredibly annoying (and an inefficient use of developer time) to have to write unit tests for simple getters and setters. I'd prefer to not exclude the whole class/package since non-trivial setters/getters should still be checked for coverage and we want to be able to pick up when current trivial code becomes non-trivial, which won't happen if it's excluded.

**Comment by rcaval** [comment] 2015-03-20 00:07
In cobertura you can use IgnoreMethodAnnotation as explained here: https://github.com/cobertura/cobertura/wiki/Ant-Task-Reference#ignore-method-annotation. In lombok you can add configurations to add @SuppressFBWarnings to generated code, which has retention policy of CLASS. Both together is a way to ignore generated methods from test coverage. Does JaCoCo have such a capability?

**Comment by Dridi** [comment] 2015-06-12 17:03
@marchof

I'm done reading this thread and the relevant links it points to. Since this is about filtering *options*, I wanted to know whether some filters would be applied systematically (basically all javac-generated false positives) while others (eg. annotation-driven) would actually *be* optional.

I opened #324 because I don't think asserts should ever be accounted for coverage, but I think that too about many use-cases you have gathered so far.

@henri-tremblay <french>Salut!</french>

What you are looking for could probably be done with some sort of post-processing hook instead. Something that could be plugged before the report generation and let you prune coverage metrics you'd consider irrelevant (with the comment stuff for instance). But I merely use jacoco so I really don't know what extension points it offers.

**Comment by whgibbo** [comment] 2015-08-13 10:27
What is the status of this issue ?

**Comment by phlogistic** [comment] 2015-08-27 14:55
Try with resources is several years old. Jacoco still doesn't support a version of Java that we can no longer download from Oracle's website?

**Comment by marchof** [comment] 2015-08-27 15:48
@phlogistic JaCoCo supports all class file versions from Java 1.1 to Java 1.8.

**Comment by phlogistic** [comment] 2015-08-27 16:59
By "support" you  mean "JaCoCo will *run* with Java 7 & 8, however if you use language syntax specific to 7 or 8, such as a try with resources block, JaCoCo will incorrectly report that block of code is not tested".

**Comment by Skeen** [comment] 2015-08-27 23:38
Hoping to see this implemented soon, having an 80% code coverage can hide a lot, while a 99% does not.

As for manual tagging hiding code coverage issues, here's a suggestion; Output the amount of code excluded in the report by yellow, but include it in the overall coverage.

**Comment by yairogen** [comment] 2015-08-31 11:57
Ia anyone working on this?

**Comment by tgolden-andplus** [comment] 2015-08-31 15:12
I have to agree with @phlogistic on this one. It's not just about try-with-resources -- Enum types are from Java *5* and they still produce uncovered code. I don't think we need a full-fledged configurable filtering solution here; some basic edge case coverage for `valueOf`/`values` would be a massive step up, then followed by try-with-resources, then any other synthetic code produced by javac.

**Comment by q3769** [comment] 2015-10-05 14:48
Hi, I have little clue of how Jacoco counts the coverage, so I have a perhaps dumb question: Why do we care about the generated code, at all? Shouldn't Jacoco count the coverage literally to the original code written by the developer, rather than the "eventual" code generated by the compiler?

**Comment by bjkail** [comment] 2015-10-05 18:10
@q3769 JaCoCo analyzes bytecode (as generated by compilers), not source code written by a developer.  That design choice is fundamental to JaCoCo and cannot be changed, so the only alternative is to add options to filter out things people don't want (note, this can be difficult for exclusions based on control-flow such as assert or try-with-resources).  e.g., assume Enum subclasses are generated by javac and assume the coverage of compiler-generated methods is unnecessary (note, these assumptions might not be true).

**Comment by q3769** [comment] 2015-10-07 19:51
@bjkail I understand that is the design choice. Starting from the bytecode, does that mean we completely lose what's in the original source code? Why can't it be accounted for retrospectively to the original code?

**Comment by bjkail** [comment] 2015-10-08 14:16
@q3769 Generally speaking, yes, the original source code is gone, so all that can be done is to use heuristics to guess what was in the original source code.  Synthetic methods are the easy and least valuable case.  For asserts, analyzing the bytecode to find branches generated by javac for assert statements and matching them to the probes inserted by JaCoCo is difficult.  For string-switch, try-finally, or try-with-resources, the bytecode analysis and matching to probes is much harder.  I can't speak for the maintainers, but I suspect a pull request would be accepted if someone solves those problems cleanly.

**Comment by SigmaX** [comment] 2015-10-09 01:48
"analyzing the bytecode to find branches generated by javac for assert statements and matching them to the probes inserted by JaCoCo is difficult"

Am I missing something, or are two issues being conflated in this thread?  The cases documented at https://github.com/jacoco/jacoco/wiki/FilteringOptions are motivated by the case where JaCoCo gets confused by funny bytecode.

So here we are, talking about bytecode.

But a number of users are asking a different question: "I have lines of code that I can *see in my source file*, like asserts, that JaCoCo is telling me have missed branches. I don't care about these missed branches, so I want these missed branches *subtracted* from the statement coverage report.

Can't filtering of some simple use cases like asserts be done via some straightforward post-processing of the report?  This would satisfy most users.

**Comment by bjkail** [comment] 2015-10-09 02:20
@SigmaX I'm not a JaCoCo maintainer, so I'll leave further replies to them, but I'll say again that deriving that kind of information from source code is contrary to the design of JaCoCo and therefore cannot be reliably implemented.  If your users are demanding this feature and you think you can satisfy them by post-processing, then you should do it, but I don't think that's the right approach for the JaCoCo project.

**Comment by acommuni** [comment] 2015-10-09 07:36
The main goal of code coverage is to identify where an effort is needed in order to fulfill code quality requierments. If the tool raises false positive "not coverage part", you cannot mastered your source code. For instance having an issue on Enum classes showing that the "valueOf" method is not covered is not relevant beacause if you do not need this "auto generated" method you do not have to test it. The goal of doing coverage on java code is not to to cover bytecode but the real java source code written by developpers. Moreover there are part of code that you know you cannot reach with unit code tests, for instance error code branches that are written in order to protect the code but is not possible to simulate the cause of entering this part of code. At the end of a developpement cycle the code coverage should be at a level of 100%, it should be reached by covering code with unit tests and ignoring part of code that you know you cannot reach them or you do not want to reach them. Then if new code are written you can check if it intoduce new "not covered part". In fact the code coverage reports  should  contain code/branch covered, code/branch not covered and code/branch considered as covered (I mean if it's filtered by a manual mark it's OK). If code coverage reports are not reliable because it show wrong issue (Enum, try catch, synchronized block, ...) you cannot control the code. The final goal of doing code coverage is not the use of coverage tool but the control your code. It's very frustrating that Jacoco is a very beautiful tool but do not fulfill real life concerns about code qualiity. Mchr3k fork is doing part of the job but it's not up to date.

**Comment by q3769** [comment] 2015-10-12 20:09
What if, after the bytecode coverage is counted as-is right now, we read in the original source code and "correct" the bytecode coverage number? 

Is that hard? If so, is there any other coverage tool that only counts the original source code coverage - the coverage of the generated code is really not that interesting.

**Comment by marchof** [comment] 2015-10-12 20:28
@q3769 There is, Clover by Atlassian works with source code instrumentation. This requires deep integration into your build cycle. Focus of JaCoCo is providing a light weight and non-intrusive tool.

**Comment by luckyincode** [comment] 2015-11-05 13:48
Wow, this conversation deviated.  I just want to ignore getters/setters.  Devs here are literally spending a time creating tests for this (which do nothing - I don't blame them).  Why has this even been open for two years?  Time to see the forest for the trees.

**Comment by McRonald** [comment] 2015-11-06 09:01
PLEASE GIVE US DEVELOPERS AT LEAST THE CHOICE!!! generated getters/setters by Lombok will be just fine, i'm not gonna test them, so i don't want to see them in my "coverage" report!

**Comment by pacey** [comment] 2016-03-15 15:12
Yeah it would be lovely to have some configuration around the Lombok auto-generate code. I have the scenario where my equals methods only have partial coverage, but the report doesn't include the generated code so I don't know which bits of the equals method is not hit. I wouldn't mind either way, show the generated code in the report or be able to exclude it from the coverage stats.

**Comment by AAverin** [comment] 2016-03-17 14:01
I would like to add Kotlin to the mix of this issue.
Kotlin has properties that would gave generated getters and setters in the bytecode. There's no meaning in testing them, but coverage values go down because of all the properties that are not covered.

Would love to have a way to ignore those

**Comment by marchof** [comment] 2016-03-17 14:40
@AAverin Added this to the list: https://github.com/jacoco/jacoco/wiki/FilteringOptions

**Comment by AAverin** [comment] 2016-03-17 14:59
@marchof Thanks!
Also, I see methods with $data_compileDebugKotlin() in the end, that should also be excluded from coverage. Such methods are also generated

**Comment by lucaswerkmeister** [comment] 2016-03-17 21:31
I don’t like how this is starting to turn into a long list of special cases for more and more languages… the class file format allows you to mark any class, field, or method as [`Synthetic`](https://docs.oracle.com/javase/specs/jvms/se8/html/jvms-4.html#jvms-4.7.8), so shouldn’t that cover most cases?

**Comment by marchof** [comment] 2016-03-17 23:32
@lucaswerkmeister Actually synthetic methods are excluded since the very first JaCoCo release. Unfortunatelly there are many more tricky reasonable cases where you want to filter certain (parts of) methods.

**Comment by andrioli** [comment] 2016-03-17 23:52
Probably, Kotlin compiler should mark these methods as synthetic. Unless the method are supposed to be available to Java files.

I don't know if synthetic methods are available for Java files (probably is not). I Guess this is the reason Lombok do not generate synthetic methods (and I guess APT do not allow generation of synthetic methods)

**Comment by marchof** [comment] 2016-03-18 06:13
Those Kotlin/Lombok methods are created for convenience usage. If they would be marked as synthetic they are not visible to the developer in IDEs any more.

**Comment by AAverin** [comment] 2016-03-18 07:31
I think it should be just a matter of adding more to 'excludes' list.
We already exclude many generated classes completely, functionality of excludes list should be just extended to support excluding methods + some additional filtering, yes

**Comment by lex-em** [comment] 2016-04-19 13:58
Hi. How I can use https://github.com/jacoco/jacoco/wiki/FilteringOptions in ant task?

**Comment by marchof** [comment] 2016-04-19 14:19
@lex-em This feature is not yet implemented.

**Comment by EoinGriffin-AI** [comment] 2016-04-20 00:31
This issue has been ongoing since 2012... :(
Sorry for the noise, but adding a +1 here for this feature. It would be so great to exclude these methods from our tests.

**Comment by lex-em** [comment] 2016-04-20 03:35
@marchof when we can expect this feature?

**Comment by lex-em** [comment] 2016-04-21 13:05
@marchof Hi, can you tell me name of jacoco agent parameter for filtering options? Does options passed as double collon separated strings?

**Comment by Godin** [comment] 2016-04-21 13:59
@lex-em This feature is not yet implemented.

**Comment by Godin** [comment] 2016-04-21 14:02
@lex-em documentation for all available agent options - http://eclemma.org/jacoco/trunk/doc/agent.html

**Comment by lex-em** [comment] 2016-04-22 03:59
@Godin does it mean that this feature is not in production?

**Comment by Godin** [comment] 2016-04-22 10:27
@lex-em as was said earlier several times - this feature IS NOT yet implemented.

**Comment by McRonald** [comment] 2016-04-22 11:49
Godin: @lex-em This feature is not yet implemented.
lex-em: @Godin does it mean that this feature is not in production?

l o l

**Comment by lex-em** [comment] 2016-04-25 05:08
lol guy is you, @McRonald :) I asked that feature has been implemented in Ant plugin, but answer was not and I asked does it already implemented.

**Comment by namero999** [comment] 2016-07-07 08:42
Pareto's principle. 80% of the devs out there want to just filter out lombok's @EqualsAndHashCode generated boilerplate, so if JaCoCo wants to narrow the scope of the filtering topic to a 20% of what it should be in order to ship something this year, my suggestion would be to implement a very basic method-name filtering. That would already make most of us (and our metrics) happy.

Also, is there an update about the status? How would you suggest to proceed in case of external contribution? Best place to study the source code?

**Comment by holiday-sunrise** [comment] 2016-08-18 12:28
How To Filter private Construtors

**Comment by Rafael-Simonelli** [comment] 2016-08-19 17:04
"cool but low priority" :´(

The tool is great, compatible with Java 8 and easy to use, the reasons I suggested it in my Company. But it's unclear... What is JaCoCo's main goal? The API or the feedback Developers need? I'm not trying to achieve 100% code coverage, but to lead my developers into the right way to test their codes, using a tool that I believe it is one of the best.

Is there a Milestone for it?

**Comment by Rafael-Simonelli** [comment] 2016-08-19 17:05
Just want the tool to ignore plain getters/setters and code generated by a compiler. :+1:

**Comment by Godin** [comment] 2016-08-19 18:07
@Rafael-Simonelli First of all - thank you for your feedback! And to everybody in this thread. We perfectly aware that this is highly awaited by our users.

However please understand us: we develop and maintain JaCoCo **absolutely for free using our free time** (weekend / night / vacation), while we also have primary job, personal life and other free open source projects.

### More specifically on a subject of priorities
For example - is it blocker for our users, when JaCoCo doesn't work on a most recent builds of JDK 8, or when it won't work with arrival of JDK 9, or when it doesn't work due to backports from JDK 9 to JDK 8? Yes, definitely. And this is "high priority". And we work on this, which BTW consumes our time and energy. Or when user can't upgrade from one version to another? Or when downstream projects such as Jenkins/NetBeans/SonarQube JaCoCo Plugins are broken because of API / behavior change considered as tiny at first, but at the end affecting thousands of users all around the world.
Now - is it blocker that some code is not marked as it is not tested and users should not or/and do not want to test it? Euh, I wouldn't say that this is blocker. Important - yes, but blocker - no. And this is "low priority" given resources we can allocate.

### More specifically on a subject of filtering
JaCoCo already filters code generated by compiler, which is easy to detected - fields and methods marked in bytecode as synthetic ones. Empty constructors in final classes, getters and setters is not a code generated by compiler. Code generated for constructions such as try-with-resource is not that easy to detect as it seems at first, you can try by yourself as an exercise and to make this more fun - try Eclipse and Oracle compilers and try their different versions.

### Wanna help?
No problem:
* Maybe teach developers about how to write good tests, which code requires more testing and which less?
* Come and help us by answering questions in users mailing list - yes, this also consumes time and energy.
* Feel free to study JaCoCo codebase and APIs to build something on top to do filtering or checking, which you need.
* And then finally maybe comeback with this as a patch to address this issue in one way or another. And yes this would require some effort to study needs of other users, so that it works not just for you,
and convince main developers that your solution is acceptable and maintainable in a long run, again given the fact of limited resources, and the fact that contributor can disappear, while his code will stay. That's IMO fair rules of the game.

Having said all this: we'll work on this as soon as it will possible, taking into account all your feedback. And thank you for your understanding.

**Comment by marchof** [comment] 2016-08-19 19:14
@Rafael-Simonelli @Godin As we now have a solution for multi-module Maven this is next on my prio list. Evgeny already explained our working mode, but hopefully I get something started till end of this year (at least an API and test framework, see compilers ;-)

**Comment by Godin** [comment] 2016-08-19 19:25
@marchof that's nice! and you know - all my time is fully yours during EclipseCon, so why not to have a coding session there ;)

**Comment by kellyfj** [comment] 2016-09-08 17:41
Add me as a person who wants this feature - due to try-with-resources coverage issues

**Comment by tr00per** [comment] 2016-09-08 19:51
"fields and methods marked in bytecode as synthetic ones" - is it possible
for Lombok to mark methods it generates as synthetic? Is there a tool that
would do that? Would Jacoco recognize such markings on non-standard methods?

czw., 8.09.2016, 19:41 użytkownik Frank J Kelly <notifications@github.com>
napisał:

**Comment by Godin** [comment] 2016-09-09 08:44
@tr00per 

> "fields and methods marked in bytecode as synthetic ones" - is it possible for Lombok to mark methods it generates as synthetic?

Probably not, because then most likely such methods will become invisible for IDEs for autocompletion. But you'd better ask Lombok developers.

> Is there a tool that would do that?

I doubt.

> Would Jacoco recognize such markings on non-standard methods?

**any** synthetic methods except lambdas are ignored by JaCoCo - https://github.com/jacoco/jacoco/blob/164485a8da42d834df4b5202079b2f2b2ac28b26/org.jacoco.core/src/org/jacoco/core/internal/analysis/ClassAnalyzer.java#L86-L89

**Comment by xasx** [comment] 2016-09-09 11:34
Bringing stuff together - see also, issue at lombok: rzwitserloot/lombok#624

**Comment by henri-tremblay** [comment] 2016-09-10 03:29
I'm pretty sure it's not a good idea. Many frameworks will treat synthetic fields specially. What is generated by lombok is actually real code. You might even want to test it to make sure the annotations are correctly placed.

**Comment by andreas-lundgren-storytel** [comment] 2016-09-15 10:27
I'm pretty sure it **is** a good idea. The exclusion of lombok code should be optional, so for projects that wants to write test to make sure the annotations generates correct code, that would still be possible. That annotations are correctly placed is verified by the compiler, incorrect annotation, no generated method to call.

Making it possible to exclude pure getters and setters, especially auto generated, will enable projects to set reasonable limits for code coverage applied to all modules (from master pom or .gradle) without having to exclude modules that only contain API DAO's.

**Comment by marchof** [comment] 2016-09-15 11:15
@andreas-lundgren-storytel I remember we discussed this before: When you mark methods as synthetic they will not be visible to in IDEs any more, e.g. for code completion. I'm not sure whether it is possible to compile against synthetic APIS. This is probably a very bad side-effect for lombok as e.g. getters/setters should be available as public API.

**Comment by tr00per** [comment] 2016-09-15 12:38
IDEA already needs a plugin to support Lombok fully, so this might not be
such a big problem.

czw., 15.09.2016, 13:15 użytkownik Marc R. Hoffmann <
notifications@github.com> napisał:

**Comment by andreas-lundgren-storytel** [comment] 2016-09-16 06:42
@marchof Sorry for being confusing, my text was a reply to previous comment stating that it shouldn't be possible to exclude getters and setters from code coverage since "You might even want to test it to make sure the annotations are correctly placed.". I wanted to show that this, according to me, is not a good argument.

We used to set a test.coverage.ratio in out parent pom, but this basically needed to be tweaked for each sub module. "This is mostly pojos, here this test ratio is applicable, this module is a lot of pojo but also logic, here this ratio is applicable" etc. Then the code changed over time but the ratio remained, typically more logic is added and the ratio should have been increased. Unless you want to write unit-test for pure getters and setters. According to me, Ideally all boilerplate getters and setters (with no logic inside) should be removed from code coverage, auto generated or not.

**Comment by marto** [comment] 2016-11-02 14:30
We use OSGi "SCR Annotations" in our code and also use (lombok) projectlombok.org as discussed above. Both these tools add methods to the classes that are pure boilerplate (similar to the getter and setter) and could be considered synthetic I guess.

Perhaps a regex capability to match method signatures could be used as a solution coupled with some sort of maximum number of instructions check (i.e. if a getter reaches more than x insturctions it's more than just a simple getter and should not be excluded).

**Comment by arosini** [comment] 2016-11-21 21:05
For people who are trying to cover Lombok code, I wrote a test class which completely covers `@Data` as a workaround. It requires some dependencies (MeanBean and EqualsVerifier if I remember correctly) and you might need to tweak so it tests the correct classes:  https://gist.github.com/arosini/5bb709da5931d600b6b7

**Comment by sjatgutzmann** [comment] 2017-01-04 18:06
https://www.bountysource.com/issues/1081222-filtering-options-for-coverage-analysis

**Comment by vincenzovitale** [comment] 2017-01-25 13:08
Hi @marchof, any news on this? 
In TomTom we are using Lombok, Jacoco and SonarQube and having this would help us a lot :)

Thanks a lot in advance,
Vincenzo.

**Comment by Gaibhne** [comment] 2017-01-26 16:15
As this issue has now been open for almost five years (!), and as far as I can tell work on the code has not even been started, maybe you could just set this issue to WontFix and delete the misleading Wiki entry that makes it seem like there is an almost finished filtering system getting ready for release ?

I get that work on open source projects is often done for free, but that doesn't mean it's nice to waste peoples time when they could have just googled "jacoco filtering" and gotten a simple "no" as a response instead of having to dig through answers on a half decade old issue thread.

**Comment by marchof** [comment] 2017-01-26 16:22
@Gaibhne This feature request is in status **open**. The wiki pages say:

> This page discusses a not yet available feature!

What exactly do you not understand here?

**Comment by marchof** [comment] 2017-01-26 16:26
@Gaibhne Nice to hear that TomTom is using JaCoCo! Unfortunately nobody is currently working on this topic. I still hope that one day we're blessed with resources and creativity to implement a powerful filtering mechanism. Cheers, -marc

**Comment by Gaibhne** [comment] 2017-01-26 16:33
Why it still says 'open'. I personally saw the elaborate Wiki and got the impression that this was a feature not yet ready for release, but clearly well along the road to maturity. It took reading through the actual comments to find out that there has been no development at all and that there aren't even concrete plans on any development ever starting.

I'm not saying it's your job to develop this feature that I want because I want it, I get that you work for free and I appreciate the work of all the amazing open source developers like you. But no one was helped by having the time of people wasted who come to the Wiki page or the top of this issue and mistakenly think they are looking at an in-dev feature that they can reasonably wait for or possibly even test and use with an edge/nightly build.

In fact, Google is full of people wasting their time making these proposed solutions work :(

**Comment by Godin** [comment] 2017-01-26 17:10
@Gaibhne sad to hear about your loss of time, but

Why this ticket exists and open: because we use issue tracker to track issues which we'd like to resolve sometime and to show that there is work for potential contributors. Tickets that will be resolved really soon are associated with exact next version explicitly. Btw exactly "open" not "in-progress".

Why wiki exists: because we use it to persist information that needs to be shared between developers, we are really far from each other - located in different countries. Moreover we believe in freedom of information and want to make sure that all discussions and insights about JaCoCo are available to the public. And moreover - we recently updated wikis to better describe bytecode that requires filtering.

We don't have important hidden discussions - even our dev mailing list can be read by anyone: https://groups.google.com/forum/#!forum/jacoco-dev

Official documentation about features that will be available in next version are on our site - http://www.jacoco.org/jacoco/trunk/doc/changes.html So please consider reading official documentation prior to googling.

**Comment by Gaibhne** [comment] 2017-01-26 19:52
Thank you for the extensive answer.

**Comment by OliWolff** [comment] 2017-02-24 09:37
Update on the lombok issue:
With lombok v1.16.14 the generated code can be annotated at byte-code level with @lombok.Generated, see https://github.com/rzwitserloot/lombok/issues/1014
The missing link is now the ability to excludes methods identified with by a configured annotation, simliar to cobertura: (sample by @Gaibhne )
```
<ignoreMethodAnnotations>
   <ignoreMethodAnnotation>lombok.Generated</ignoreMethodAnnotation>
</ignoreMethodAnnotations>
```

**Comment by t1** [comment] 2017-03-09 04:42
Is anybody working on this already? I took a look and found a place where I'd put it. I assume the main work would be to transport the config to the agent, but that looks straight forward, too. I quite like the code, actually :-)

And is it okay to discuss this here?

**Comment by marchof** [comment] 2017-03-09 06:12
@t1 Except anylysis of the cases (see [wiki](https://github.com/jacoco/jacoco/wiki/FilteringOptions)) we're not working on this. Also

* @mfriedenhagen created [a project](https://github.com/mfriedenhagen/org.jacoco.filteringsamples) to create test classes with different compilers
* @marchof played with [bytecode pattern matching](https://github.com/marchof/jacoco-playground-filters)

> I assume the main work would be to transport the config to the agent

Actually filtering should happen at analysis time. Therefore the agent does not need any parameters for filtering.

From my point of view the main work is to efficiently match bytecode patterns and design an API that allows to hook filters into the analysis process. Any clever idea is welcome here!

**Comment by t1** [comment] 2017-03-09 06:58
@marchof: Thanks for the fast feedback. The FilteringOptions have a different scope, I guess. I want to add a configuration to the maven plugin to set the annotations that make the `ClassInstrumenter#visitMethod` skip instrumentation. Following Coverturas lead, I'd use something like this in the pom:

```xml
<configuration>
  <instrumentation>
    <ignoreMethodAnnotations>
      <ignoreMethodAnnotation>lombok.Generated</ignoreMethodAnnotation>
    </ignoreMethodAnnotations>
  </instrumentation>
</configuration>
```

Lombok is the use case I have at hand, but there are other code generators using different annotations, so this configuration would have to be moved to the agent, wouldn't it?

I'll take a look, if I can make it work.

**Comment by marchof** [comment] 2017-03-09 09:40
@t1 The agent always instruments all methods. Whether a method is included in the coverage report is a plain decission at analysis time. If we would adjust instrumentation in addition, we would need to always configure both places (agent and analysis) always the exact way. Note: Exec files do not come with any meta information about the probes. Probes are derived from the structure of the class file only. Therefore this process must create the same results at instrumentation and analysis time. See section "Why can't JaCoCo simply use the class name to identify classes?" here http://www.jacoco.org/jacoco/trunk/doc/classids.html

**Comment by t1** [comment] 2017-03-10 21:45
@marchof: Oh, I was on the wrong track. Thanks for the hint.

I've reconsidered what you where saying and it's probably more according to the JaCoCo philosophy that JaCoCo should be smart, and not every developer be forced to know and consider and configure things like this. So it's probably _even better_ to hard code the `lombok.Generated` annotation.

**Comment by davidburkhart** [comment] 2017-09-27 13:00
Are there any plans on implementing and releasing the filtering feature? Last comment is 6 months old...

**Comment by marchof** [comment] 2017-09-27 14:55
@davidburkhart We're actively working on filters. See our change log what is already available on snapshot builds: http://www.jacoco.org/jacoco/trunk/doc/changes.html
We might be able to do a release this year.

**Comment by marchof** [comment] 2017-09-27 14:57
To not confuse people I'm closing this issue as we're using separate PRs for specific filtering scenarios now.

**Closed as completed** 2017-09-27 14:57 UTC
Labels: type: enhancement, component: core.filters

**Comment by abinet** [comment] 2017-10-19 08:20
What about ignoring main methods for SpringBootApplication? 

For this class I get 0% coverage.

```
@SpringBootApplication
public class MyApplication {

	public static void main(String[] args) {
		SpringApplication.run(MyApplication.class, args);
	}
}
```

**Comment by t1** [comment] 2017-10-19 08:27
@abinet: I'm not sure if I get your question right: You have a SpringBootApplication that you _do_ test, but not the `main` method itself? I guess that you _could_ write some extra logic in that main method, even if it's not idiomatic. It's not generated code, after all, so you should write a test covering this. Or even better, add a feature to Lombok to generate the main method! That would solve not only the coverage problem, but also remove that boiler plate code ;-)

**Comment by abinet** [comment] 2017-10-19 08:38
@t1  Thanks for the answer. You got the point right but it looks too dogmatic for me.

**Comment by sshcherbakov** [comment] 2017-10-19 08:52
@t1 that actually means, that to get 100% test coverage, we _must_ run the full application necessarily starting from the main method, even when its complete code (except one liner starter that only calls third party Spring Boot code) is 100% test covered.
It would not be a problem in this particular case of a single liner that Spring Boot framework rightfully requires, if we could exclude that method from code coverage check. But it seems that it is not possible to do either.
So we are forced to spend significant effort on testing Spring Boot Framework instead of concentrating on the application code.

**Comment by t1** [comment] 2017-10-19 09:58
I don't think that forcing 100% coverage is generally worth the effort. I'd just live with 99% in this case ;-)

But I guess you could just as well simply cheat by manually annotating the `main` method as `@lombok.Generated`.

Just to make my point clear: I don't think that JaCoCo should assume that there never will be any logic in a Spring-Boot main method; just as it should not assume that there never will be any logic in a getter. These things are real code written by hand, so they _can_ contain bugs, and they _should_ be covered. Only when things are _generated_ (synthetic code, lombok generated, etc.), then JaCoCo should not count them as uncovered; we can assume that the tools generating the code are okay.

**Comment by SchulteMarkus** [comment] 2017-10-19 10:12
@abinet 
In my opinion, the execution of this main()-method should be done in the integration-test-phase of your Maven-build. I am not familiar with Gradle, but I hope, they got something similar. 
You could bind your jacoco-report not to end after test-phase, but after integration-test-phase (IMO bad pattern), this way the execution of your main()-method will be recorded and part of your JaCoCo-report.

A little bit off-topic...
If you want to integration-test your Spring-application, build as a docker-image, maybe you want to have a look at my repo [SchulteMarkus/docker-compose-rule-spark-demo](https://github.com/SchulteMarkus/docker-compose-rule-spark-demo). In this repo, Java-spark is used, not Spring, but it should be easy to adapt (as this testing is about a jar-file, in this case from Java-spark, in your case form Spring). For testing, HTMLUnit is used.
