### ISSUE TITLE
Support SMAP generated by Kotlin 1.5 compiler (Support JSR-45 spec)

### ISSUE THREAD

**Issue by max-kammerer** [jacoco/jacoco#1155] opened 2021-02-17 13:32 UTC
Prior version 1.5 Kotlin compiler violate  JSR-45 specification in case of several stratum presence that was fixed in 1.5. There was a problem with `*E` presence between stratums which according to specification should be presented only at the end of SMAP (more details could be found in https://youtrack.jetbrains.com/issue/KT-37704).

Now proper SMAP output breaks JaCoCo parser with `Unexpected SMAP line: *S KotlinDebug` exception.
Repro project could be found in https://youtrack.jetbrains.com/issue/KT-44757

**Comment by Godin** [comment] 2021-02-17 16:02
Reduced reproducer:

for `Example.kt`

```
inline fun f() {}
fun g() = f()
```

execution of

```
./kotlin-1.4.30/bin/kotlinc -language-version 1.5 Example.kt

java -jar ./jacoco-0.8.6/lib/jacococli.jar classinfo ExampleKt.class
```

fails with

```
Exception in thread "main" java.io.IOException: Error while analyzing ExampleKt.class.
Caused by: java.lang.IllegalStateException: Unexpected SMAP line: *S KotlinDebug
```

**Comment by maranathaaa** [comment] 2021-02-25 09:15
hello, can You provide supposed data when 0.8.7 will be released?

**Comment by Godin** [comment] 2021-02-25 09:22
> hello, can You provide supposed data when 0.8.7 will be released?

@maranathaaa please see https://www.jacoco.org/jacoco/trunk/doc/faq.html

> ### When will feature X be released?
> JaCoCo is maintained by volunteers in their free time. Since we cannot guarantee free capacity, we do not commit to particular release dates. Typically, you can expect a couple of releases every year.
>
> In the change log, you can see all features that have been implemented in master branch and will be available with the next release. And in the meantime you can test latest build of master branch ([Maven SNAPSHOT](https://www.jacoco.org/jacoco/trunk/doc/repo.html)) and provide feedback to us.

**Closed** 2021-03-16 10:43 UTC
Labels: component: core.filters, type: bug :bug:

**Comment by michaelbrewer** [comment] 2021-05-02 03:45
When will this be fixed for Gradle and Kotlin 1.5?

**Comment by overfullstack** [comment] 2021-05-02 03:47
This issue still exists. When can we expect a fix?

**Comment by marchof** [comment] 2021-05-02 07:18
Just check the [FAQ](https://www.jacoco.org/jacoco/trunk/doc/faq.html):

**When will feature X be released?**

JaCoCo is maintained by volunteers in their free time. Since we cannot guarantee free capacity, we do not commit to particular release dates. Typically, you can expect a couple of releases every year.

In the change log, you can see all features that have been implemented in master branch and will be available with the next release. And in the meantime you can test latest build of master branch (Maven SNAPSHOT) and provide feedback to us.

**Comment by marcust** [comment] 2021-05-02 08:59
It is fixed in the next version, so you have to wait until 0.8.7 is released. In urgent cases you can start using the `0.8.7-SNAPSHOT` available via [Snapshot Builds](https://www.jacoco.org/jacoco/)

**Comment by Godin** [comment] 2021-05-05 09:55
[JaCoCo `0.8.7` has been released](https://twitter.com/_godin_/status/1389728203342757891)

**Comment by laalto** [comment] 2021-05-05 12:16
Seeing this issue with kotlin 1.5.0 and jacoco 0.8.7. 

```
Caused by: java.lang.IllegalStateException: Unexpected SMAP line: *S KotlinDebug
        at org.jacoco.core.internal.analysis.filter.KotlinInlineFilter.getFirstGeneratedLineNumber(KotlinInlineFilter.java:98)
        at org.jacoco.core.internal.analysis.filter.KotlinInlineFilter.filter(KotlinInlineFilter.java:44)
        at org.jacoco.core.internal.analysis.filter.Filters.filter(Filters.java:58)
        at org.jacoco.core.internal.analysis.ClassAnalyzer.addMethodCoverage(ClassAnalyzer.java:119)
        at org.jacoco.core.internal.analysis.ClassAnalyzer.access$100(ClassAnalyzer.java:33)
        at org.jacoco.core.internal.analysis.ClassAnalyzer$1.accept(ClassAnalyzer.java:108)
        at org.jacoco.core.internal.flow.ClassProbesAdapter$2.visitEnd(ClassProbesAdapter.java:91)
        at org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1288)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:688)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:400)
        at org.jacoco.core.analysis.Analyzer.analyzeClass(Analyzer.java:116)
        at org.jacoco.core.analysis.Analyzer.analyzeClass(Analyzer.java:132)
```

**Comment by Godin** [comment] 2021-05-05 12:19
@laalto 

> at org.jacoco.core.internal.analysis.filter.KotlinInlineFilter.getFirstGeneratedLineNumber(KotlinInlineFilter.java:98)

you can't have such stack trace when you really use JaCoCo 0.8.7, because in 0.8.7 `throw` is not located on line 98, but on line 102

https://github.com/jacoco/jacoco/blob/v0.8.7/org.jacoco.core/src/org/jacoco/core/internal/analysis/filter/KotlinInlineFilter.java#L102

**Comment by laalto** [comment] 2021-05-05 12:34
Yeah, that's interesting. Using the jacoco gradle plugin with `classpath "org.jacoco:org.jacoco.core:0.8.7"` in project-level build.gradle. Digging deeper

**Comment by Godin** [comment] 2021-05-05 12:39
> Using the jacoco gradle plugin with classpath "org.jacoco:org.jacoco.core:0.8.7"

Regarding https://docs.gradle.org/current/userguide/jacoco_plugin.html
please see https://github.com/jacoco/jacoco/pull/1164#issuecomment-832562229 that states the same as in mentioned above Gradle documentation:
[`jacoco.toolVersion` can be set to non-default value to use specific version including `0.8.7`](https://docs.gradle.org/7.0/dsl/org.gradle.testing.jacoco.plugins.JacocoPluginExtension.html)

For the other Gradle plugins, please refer to their documentation.

**Comment by laalto** [comment] 2021-05-05 13:16
Thanks for the quick responses. Looks like the project had some legacy to be updated in its jacoco setup. `jacoco.toolVersion` didn't work though, needed to use a construct like in https://stackoverflow.com/questions/63479850/jacoco-gradle-plugin-ignoring-version to force 0.8.7 to be used and to get migration to kotlin 1.5.0 proceed further.

**Comment by hbb20** [comment] 2021-05-18 21:51
> Thanks for the quick responses. Looks like the project had some legacy to be updated in its jacoco setup. `jacoco.toolVersion` didn't work though, needed to use a construct like in https://stackoverflow.com/questions/63479850/jacoco-gradle-plugin-ignoring-version to force 0.8.7 to be used and to get migration to kotlin 1.5.0 proceed further.

@laalto Even that is not working for me.. still seeing error on line 98 means it's not using 0.8.7. Any ideas why or what else can I try?

**Comment by mohamed-khaled-hsn** [comment] 2021-06-07 12:08
> > Thanks for the quick responses. Looks like the project had some legacy to be updated in its jacoco setup. `jacoco.toolVersion` didn't work though, needed to use a construct like in https://stackoverflow.com/questions/63479850/jacoco-gradle-plugin-ignoring-version to force 0.8.7 to be used and to get migration to kotlin 1.5.0 proceed further.
> 
> @laalto Even that is not working for me.. still seeing error on line 98 means it's not using 0.8.7. Any ideas why or what else can I try?

This worked in my case:
If you have a multi-module project, you can specify jacoco toolVersion in `allProjects`
```
allprojects {
    jacoco {
        toolVersion = "0.8.7"
    }
    //..
}
```

**Comment by Maksym-Motornyi** [comment] 2021-06-10 22:04
To force use 0.8.7 version just add this to the project level gradle file:
```
subprojects {
    configurations.all {
        resolutionStrategy {
            eachDependency { details ->
                if ('org.jacoco' == details.requested.group) {
                    details.useVersion "0.8.7"
                }
            }
        }
    }
}
```

**Comment by xghita** [comment] 2021-06-11 09:00
@Maksym-Motornyi  Still got the error on line 98

```
java.lang.IllegalStateException: Unexpected SMAP line: *S KotlinDebug
	at org.jacoco.core.internal.analysis.filter.KotlinInlineFilter.getFirstGeneratedLineNumber(KotlinInlineFilter.java:98)
```

which by @Godin  comment (https://github.com/jacoco/jacoco/issues/1155#issuecomment-832642347 ) means the project is still not using 0.8.7 version. 

In my case is working fine when I run tests local with Android studio, but got the issue on a remote Jenkins machine.

**Comment by NikolayMetchev** [comment] 2021-06-11 09:32
Have you updated the Jenkins Jacoco plugin https://plugins.jenkins.io/jacoco/?

**Comment by xghita** [comment] 2021-06-11 12:07
> Have you updated the Jenkins Jacoco plugin https://plugins.jenkins.io/jacoco/?

thank you! updating to 3.2.0 has fixed it.
