### ISSUE TITLE
java/lang/IllegalAccessError; thrown while initializing Lorg/jacoco/agent/rt/internal_8ff85ea/Offline

### ISSUE THREAD

**Issue by trebouillon** [jacoco/jacoco#620] opened 2017-11-09 13:48 UTC
This is a issue tracker. Please use our mailing list for general questions: 
https://groups.google.com/forum/?fromgroups=#!forum/jacoco

Also check FAQ before opening an issue: http://www.jacoco.org/jacoco/trunk/doc/faq.html

### Steps to reproduce

JaCoCo version: 0.7.9
Operating system: macOS sierra
Tool integration: Gradle 4.3, Java8 (also set in Gradle as source and target), Build Tools Gradle 3.0.0

Run Android Test with code coverage enabled on Emulators <= 19 (KitKat).

### Expected behaviour

Tests are starting and running.

### Actual behaviour

```
Class resolved by unexpected DEX: Lorg/jacoco/agent/rt/internal_8ff85ea/IExceptionLogger$1;(0xa68fd368):0x98bd5000 ref [Lcom/google/devtools/build/android/desugar/runtime/ThrowableExtension;] Lcom/google/devtools/build/android/desugar/runtime/ThrowableExtension;(0xa68fd368):0x99154000
11-09 14:18:40.252 W/dalvikvm( 1155): (Lorg/jacoco/agent/rt/internal_8ff85ea/IExceptionLogger$1; had used a different Lcom/google/devtools/build/android/desugar/runtime/ThrowableExtension; during pre-verification)
11-09 14:18:40.252 W/dalvikvm( 1155): Exception Ljava/lang/IllegalAccessError; thrown while initializing Lorg/jacoco/agent/rt/internal_8ff85ea/Offline;
11-09 14:18:40.252 D/AndroidRuntime( 1155): Shutting down VM
11-09 14:18:40.252 W/dalvikvm( 1155): threadid=1: thread exiting with uncaught exception (group=0xa62dc288)
11-09 14:18:40.252 E/AndroidRuntime( 1155): FATAL EXCEPTION: main
11-09 14:18:40.252 E/AndroidRuntime( 1155): java.lang.ExceptionInInitializerError
11-09 14:18:40.252 E/AndroidRuntime( 1155): 	at my.cool.app.Application.$jacocoInit(SearchApplication.java)
11-09 14:18:40.252 E/AndroidRuntime( 1155): 	at my.cool.app.Application.<init>(Application.java)
11-09 14:18:40.252 E/AndroidRuntime( 1155): 	at java.lang.Class.newInstanceImpl(Native Method)
11-09 14:18:40.252 E/AndroidRuntime( 1155): 	at java.lang.Class.newInstance(Class.java:1319)
11-09 14:18:40.252 E/AndroidRuntime( 1155): 	at android.app.Instrumentation.newApplication(Instrumentation.java:982)
11-09 14:18:40.252 E/AndroidRuntime( 1155): 	at android.app.Instrumentation.newApplication(Instrumentation.java:967)
11-09 14:18:40.252 E/AndroidRuntime( 1155): 	at android.app.LoadedApk.makeApplication(LoadedApk.java:496)
11-09 14:18:40.252 E/AndroidRuntime( 1155): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4124)
11-09 14:18:40.252 E/AndroidRuntime( 1155): 	at android.app.ActivityThread.access$1300(ActivityThread.java:130)
11-09 14:18:40.252 E/AndroidRuntime( 1155): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1255)
11-09 14:18:40.252 E/AndroidRuntime( 1155): 	at android.os.Handler.dispatchMessage(Handler.java:99)
11-09 14:18:40.252 E/AndroidRuntime( 1155): 	at android.os.Looper.loop(Looper.java:137)
11-09 14:18:40.252 E/AndroidRuntime( 1155): 	at android.app.ActivityThread.main(ActivityThread.java:4745)
11-09 14:18:40.252 E/AndroidRuntime( 1155): 	at java.lang.reflect.Method.invokeNative(Native Method)
11-09 14:18:40.252 E/AndroidRuntime( 1155): 	at java.lang.reflect.Method.invoke(Method.java:511)
11-09 14:18:40.252 E/AndroidRuntime( 1155): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
11-09 14:18:40.252 E/AndroidRuntime( 1155): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
11-09 14:18:40.252 E/AndroidRuntime( 1155): 	at dalvik.system.NativeStart.main(Native Method)
11-09 14:18:40.252 E/AndroidRuntime( 1155): Caused by: java.lang.IllegalAccessError: Class ref in pre-verified class resolved to unexpected implementation
11-09 14:18:40.252 E/AndroidRuntime( 1155): 	at org.jacoco.agent.rt.internal_8ff85ea.IExceptionLogger$1.logExeption(IExceptionLogger.java:25)
11-09 14:18:40.252 E/AndroidRuntime( 1155): 	at org.jacoco.agent.rt.internal_8ff85ea.Agent.startup(Agent.java:127)
11-09 14:18:40.252 E/AndroidRuntime( 1155): 	at org.jacoco.agent.rt.internal_8ff85ea.Agent.getInstance(Agent.java:50)
11-09 14:18:40.252 E/AndroidRuntime( 1155): 	at org.jacoco.agent.rt.internal_8ff85ea.Offline.<clinit>(Offline.java:31)
11-09 14:18:40.252 E/AndroidRuntime( 1155): 	... 18 more
11-09 14:18:40.252 W/ActivityManager(  322): Error in app de.mobile.android.app.debug running instrumentation ComponentInfo{de.mobile.android.app.tests/android.support.test.runner.AndroidJUnitRunner}:
11-09 14:18:40.252 W/ActivityManager(  322):   java.lang.IllegalAccessError
11-09 14:18:40.252 W/ActivityManager(  322):   java.lang.IllegalAccessError: Class ref in pre-verified class resolved to unexpected implementation
11-09 14:18:40.252 I/ActivityManager(  322): Force stopping package de.mobile.android.app.debug uid=10048
11-09 14:18:40.252 I/ActivityManager(  322): Killing proc 1155:de.mobile.android.app.debug/u0a48: force stop
```

**Comment by Godin** [comment] 2017-11-09 17:25
Looking on a results of search "java.lang.IllegalAccessError: Class ref in pre-verified class resolved to unexpected implementation" in Google, I have a strong feeling that you have missconfiguration/inconsistency in your build. But unless you provide clean reproducer, hard to say what's wrong exactly.

**Comment by trebouillon** [comment] 2017-11-10 07:45
Of course, I thought the same and used Google a lot. I also searched for duplicate DEX files and I use forced resolution strategy to avoid different versions. Would it be worth to share my gradle config and maybe the dependency tree?

**Comment by Godin** [comment] 2017-11-10 07:47
@trebouillon 

> Would it be worth to share my gradle config and maybe the dependency tree?

complete runnable reproducer

**Comment by trebouillon** [comment] 2017-11-10 08:11
Ok, I need to prepare this first :)

**Comment by Godin** [comment] 2017-11-30 23:43
@trebouillon Without the requested information we cannot analyze this. Feel free to reopen if you can provide it. Thank you for your understanding.

**Comment by trebouillon** [comment] 2017-12-01 07:16
Totally fine. I wanted to suggest the same. I didn't had time to provide a reproducible app. If so I will reopen the issue.

**Comment by RodrigoAmaroEng** [comment] 2017-12-13 13:33
Hey @Godin
I have exactly the same output on same environment (JaCoCo, Gradle, Java and Android Gradle plugin versions). I noticed that It started right after i upgraded to Android Studio 3.0 only with devices before API Level 20 (Real ones or Emulators).

I was writing a new project to provide a reliable way to check this problem when i noticed that putting the following lines is what triggers the problem:

<pre>
compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
}
</pre>

Anyway i uploaded this project on the following address so anyone can check.
https://github.com/RodrigoAmaroEng/JacocoBugProof

**Comment by Godin** [comment] 2017-12-14 20:15
@RodrigoAmaroEng first of all thank you for reproducer and details about device! :thumbsup:

I'm attaching it here for the record - [issue-620-reproducer.zip](https://github.com/jacoco/jacoco/files/1560577/issue-620-reproducer.zip)

Indeed using following virtual device

```
$ android list avd
Available Android Virtual Devices:
    Name: Test1
  Device: Nexus 4 (Google)
    Path: /Users/evgeny.mandrikov/.android/avd/Test1.avd
  Target: Android 4.4.2 (API level 19)
 Tag/ABI: default/armeabi-v7a
    Skin: 768x1280
```

issue is reproducible:

```
$ git clone https://github.com/RodrigoAmaroEng/JacocoBugProof
$ cd JacocoBugProof
$ git rev-parse HEAD
433cca81e12693bae6d4d66f391f4cc69d4a23bc

$ java --version
java version "1.8.0_152"
Java(TM) SE Runtime Environment (build 1.8.0_152-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.152-b16, mixed mode)

$ ./gradlew --version

------------------------------------------------------------
Gradle 4.1
------------------------------------------------------------

Build time:   2017-08-07 14:38:48 UTC
Revision:     941559e020f6c357ebb08d5c67acdb858a3defc2

Groovy:       2.4.11
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_152 (Oracle Corporation 25.152-b16)
OS:           Mac OS X 10.11.6 x86_64

$ ./gradlew clean connectedAndroidTest
> Task :app:connectedDebugAndroidTest
Starting 1 tests on Test1(AVD) - 4.4.2

jacoco.bug.com.jacocobugproof.ExampleInstrumentedTest > useAppContext[Test1(AVD) - 4.4.2] FAILED
        java.lang.IllegalAccessError: Class ref in pre-verified class resolved to unexpected implementation
        at org.jacoco.agent.rt.internal_773e439.IExceptionLogger$1.logExeption(IExceptionLogger.java:25)
Tests on Test1(AVD) - 4.4.2 failed: Instrumentation run failed due to 'java.lang.IllegalAccessError'


FAILURE: Build failed with an exception.
```

However with following virtual device

```
$ android list avd
Available Android Virtual Devices:
    Name: Test2
  Device: Nexus 4 (Google)
    Path: /Users/evgeny.mandrikov/.android/avd/Test2.avd
  Target: Android 5.0.1 (API level 21)
 Tag/ABI: default/armeabi-v7a
    Skin: 768x1280
```

there is no problem:

```
$ ./gradlew clean connectedAndroidTest
Starting 1 tests on Test2(AVD) - 5.0.2

BUILD SUCCESSFUL in 2m 14s
59 actionable tasks: 58 executed, 1 up-to-date
```

BTW, @RodrigoAmaroEng, should be mentioned that declaration
```
jacoco {
  toolVersion = "0.7.9"
}
```
in your `build.gradle` affects only Java Plugin for Gradle, but doesn't affect Android Plugin for Gradle, which actually uses "0.7.4" as package name in stacktrace indicates (`org.jacoco.agent.rt.internal_773e439`) and as can be seen in debug output of Gradle. And seems that usage of different versions in Java Plugin and Android Plugin can cause troubles in some scenarios - see https://stackoverflow.com/a/47041368/244993 , which also explains how to specify version for Android Plugin.

So first I tried to use `0.7.9`, but this didn't helped:
```
$ ./gradlew clean connectedAndroidTest
> Task :app:connectedDebugAndroidTest
Starting 1 tests on Test1(AVD) - 4.4.2

jacoco.bug.com.jacocobugproof.ExampleInstrumentedTest > useAppContext[Test1(AVD) - 4.4.2] FAILED
        java.lang.IllegalAccessError: Class ref in pre-verified class resolved to unexpected implementation
        at org.jacoco.agent.rt.internal_8ff85ea.IExceptionLogger$1.logExeption(IExceptionLogger.java:25)
Tests on Test1(AVD) - 4.4.2 failed: Instrumentation run failed due to 'java.lang.IllegalAccessError'


FAILURE: Build failed with an exception.
```

Independently of the version, stack trace indicates that exception happens on a line https://github.com/jacoco/jacoco/blob/ec516e47462e617443f1f3c368e0faaa48ff85ea/org.jacoco.agent.rt/src/org/jacoco/agent/rt/internal/IExceptionLogger.java#L25

So then I tried to use JaCoCo build, where this line is replaced by
```
System.out.println(ex);
```
and 💥  **magically** this helps ✨ 

I don't see any reasons why innocent invocation of `Exception#printStackTrace()` can't be done here on Android, only on devices before API Level 20 and only when source and target compatibility set to Java 8 😕  But I'm not (as well as @marchof) Android expert. @allenhair maybe you have an idea?

Given the above I'm not so eager to do blind changes just based on such observation/try.

Also should be mentioned that according to page https://developer.android.com/studio/write/java8-support.html :

> the default toolchain implements the new language features by performing bytecode transformations, called desugar, on the output of the javac compiler

> If you’re experiencing issues related to the support for Java 8 language features, you can disable it 

> To help us improve support for Java 8, please file a bug.

so maybe there is a bug in their transformations or device image that is worth to be reported to Android platform developers? @RodrigoAmaroEng, as you're one of the reporters of this problem here and one of affected users, may I ask you [to report this to them](https://developer.android.com/studio/report-bugs.html) and then share a link on a ticket here? Thanks in advance.

**Comment by RodrigoAmaroEng** [comment] 2017-12-14 20:59
@Godin thanks for the feedback! :+1: 

I'm aware that turning off Java 8 features solves the problem, but for us it's not an option.

I've already filled the report at Google's page... while i wait them to analyze the problem i'll gonna check what can be causing this only on these devices.

I know that, since API 20, Android changed its runtime environment from Dalvik to ART along with the support addition for 64 bits systems though it's not clear to me if some of these things are related

**Comment by Godin** [comment] 2017-12-14 22:28
> I've already filled the report at Google's page

Is it browsable publicly? can you post a link here?

**Comment by RodrigoAmaroEng** [comment] 2017-12-14 22:38
Yeah sure, https://issuetracker.google.com/issues/70678714

**Comment by trebouillon** [comment] 2017-12-15 16:31
Thanks for reopening and providing the required info @RodrigoAmaroEng

**Comment by Godin** [comment] 2018-01-11 22:19
https://issuetracker.google.com/issues/70678714 has been marked as duplicate of https://issuetracker.google.com/issues/71737186 , which in his turn states that fix will be in the next version of the Android plugin for Gradle. Therefore I'm closing this ticket.

**Closed by Godin** 2018-01-11 22:19 UTC
Labels: feedback pending, help wanted
