### ISSUE TITLE
Kotlin compiler should mark anonymous classes for callable references as synthetic

### ISSUE THREAD

**Issue by thimmwork** [jacoco/jacoco#791] opened 2018-11-19 10:48 UTC
Kotlin generates additional classes when using reflection. These classes are neither marked as covered nor filtered out by jacoco.

### Steps to reproduce
Add maven dependency
```
        <dependency>
            <groupId>org.jetbrains.kotlin</groupId>
            <artifactId>kotlin-reflect</artifactId>
            <version>${kotlin.version}</version>
        </dependency>
```

and create a function which gets a reflect.Method reference to a function like this:
```
fun minimalFunction() {
    // this will make jacoco fail due to a class generated by kotlin
    ::minimalFunction.javaMethod
}
```

when using `.javaMethod`, Kotlin generates an anonymous class which will be checked for line coverage by jacoco

JaCoCo version: 0.8.2
Operating system: any (tested on Mac OS 10.13.6 and Ubuntu)
Tool integration: Maven

### Expected behaviour
Code generated by Kotlin compiler should be marked as covered or filtered out

### Actual behaviour
Line coverage for generated class is 0.00
`Rule violated for class SomeController.getAddressWithGeoInformation.javaMethod.1: lines covered ratio is 0.00, but expected minimum is 0.85`

![image](https://user-images.githubusercontent.com/27409890/48702301-e0bd9780-ebf0-11e8-8487-befb46098ddf.png)

This issue may or may not affect other reflection mechanisms as well. I tested only `.javaMethod` as we use this for generating HATEOAS links in our web controller classes.

**Comment by Godin** [comment] 2018-11-19 13:39
Generation of class is not caused by `.javaMethod`, but by a method reference:

```
fun main(args: Array<String>) {
    println(::main)
}
```

@thimmwork following questions must be answered before considering implementation of filter: why Kotlin compiler adds line numbers into generated class? and most importantly why it is not marked as `synthetic`? CC @goodwinnk

**Comment by goodwinnk** [comment] 2018-11-26 17:29
I have just created https://youtrack.jetbrains.com/issue/IDEA-202972 and will let you know about updates.

**Comment by Godin** [comment] 2019-01-07 16:05
@goodwinnk I noticed that [there is already change that marks method as `synthetic`](https://github.com/JetBrains/kotlin/commit/c1ef89df2c4c49321baaaa1a103a8ab9625e6613). Thanks a lot for this! 👍 ❤️

I'm wondering why was decided to keep line number in this method, while you was questioning its necessity in description of [KT-28453](https://youtrack.jetbrains.com/issue/KT-28453) ? Could be noted that the only known to me so far examples of `synthetic` methods with line numbers are for default arguments and for suspending functions, and they should not be filtered by JaCoCo - see #774 and #804 , whereas all methods without line numbers should be filtered - see yours #689 And hence maybe removal of line number will make things more consistent in design of code generator? :wink: And in case of such consistency we can simplify code of filtering.

BTW maybe you can point me on other examples of `synthetic` methods in Kotlin to grow our validation test suite and knowledge? Will appreciate this.

**Comment by Godin** [comment] 2019-01-28 10:39
@goodwinnk thanks!

**Comment by Godin** [comment] 2019-03-01 16:11
@thimmwork could you please try [Kotlin 1.3.30 EAP](https://discuss.kotlinlang.org/t/kotlin-1-3-30-early-access-preview/11780) that contains fix for [KT-28453](https://youtrack.jetbrains.com/issue/KT-28453) ? According to my tests callable references do not cause partial coverage after this fix.

**Comment by thimmwork** [comment] 2019-03-01 20:28
@Godin I updated kotlin-maven-plugin and stdlib to 1.3.30-eap-11 and it works. 😃 
Jacoco no longer reports the generated class as uncovered.
However, for some reason it still reports the source line with the method reference as uncovered.
But this may or may not be a different issue. Also it is easy to find a workaround as it now affects hand-written classes.

Thank you very much @goodwinnk and @Godin !

**Comment by Godin** [comment] 2019-04-17 15:33
Added validation test which shows that after upgrade to Kotlin 1.3.30 callable references do not cause partial coverage - https://github.com/jacoco/jacoco/commit/d3c47652b89267709aae04bec66a68bdf6df9670

**Closed by Godin** 2019-04-17 15:33 UTC
Labels: component: core.filters
