### ISSUE TITLE
Some classes are incorrectly reported with zero coverage (No mocking framework)

### ISSUE THREAD

**Issue by dimitris-athanasiou** [jacoco/jacoco#383] opened 2016-02-24 16:01 UTC
I am running integration tests against my application, which is a JAX-RS application deployed on Jetty. The execution data is collected by attaching a jacoco agent (0.7.5) to the JVM. The application has 300+ classes. I observe that a handful of them is reported to have zero coverage although that is impossible. The coverage is reported by Sonar after feeding it the exec file.

In order to get a better sense of what is going on, I manually generated a jacoco report using the ant task. I observed the message "Execution data for class <class-path> does not match". I read about the class IDs and the reasons I could have different id between the runtime class and the source file. Also, since I am using Jetty, I thought that could be the reason some classes are instrumented upon loading.

I tried repeating the jenkins job that runs the integration tests, collects the coverage and runs sonar on my local machine. Instead of running the application via an install (and thus the jars), I run it straight from Eclipse. I attached the jacoco agent, run the tests, created a report (matching against the .class files) and I got non-zero (and seemingly accurate) coverage reported for previously unmatched files. I also created the report from the same exec file but this time matching against the jar files and coverage was again 0 for those files.

I also tried to speculate what the unmatched classes have in common that could point to what instruments them. However, what drives me crazy is that I can't find such a common pattern among those. For example, one of the classes belongs in a package with other very similar classes. They all extend the same super class and they are used in the same way and share same set of imports. I cannot understand why some are getting matched and some aren't. Even more crazy is the fact that one of this classes that has non-zero coverage reported is only ever called by one of the other classes that has zero coverage! Another example is a class that is simply declaring String constants. The only other thing that class does is loading a ResourceBundle.

Unfortunately, it's impossible for me to share code. I know this means I am asking you to find a needle in a haystack, but any ideas about what is going on would be highly appreciated. Thank you in advance.

**Comment by marchof** [comment] 2016-02-24 17:38
By any chance, are you using Pack200 to create your JAR files? Also the classdumpdir agent option helps to analyze the classes the agent actually sees and diff them with the original classes.

BTW, for general questions we have a public mailing list: https://groups.google.com/forum/?fromgroups=#!forum/jacoco

**Comment by dimitris-athanasiou** [comment] 2016-02-25 17:12
Thank you for the suggestion of using the classdumpdir. Thanks to that, I used javap command to create the disassembly of the two different class files (the one seen by jacoco-agent and the one compiled by mvn directly). The difference was revealing and it probably is something that jacoco needs to address.

**The problem is lambdas**. Lambda expressions get a name like "com.mycompany.MyClass$$Lambda$8/398572781". The difference in my two files is **the number after the last dollar sign.** 

Even more interestingly, it looks like the numbering differs depending on the full path of the source files. I would speculate that javac somehow puts the source files in an HashMap or something where the key is the full path resulting to a different order of compilation and thus, different numbering of lambda expressions. In my case, the build is created by one jenkings job, but the sonar update is fired through a different jenkins job resulting in different directories containing the source files.

Could the problem be fixed if jacoco would preprocess the class files omitting the numbers in lambda names? Then the class-id hash would not depend on something as volatile as the directory structure of the compilation.

Let me know how to proceed with this, if I should create a new ticket or reopen and edit the title of this one.

**Comment by Godin** [comment] 2016-02-25 17:19
@dimitris-athanasiou could you please provide small example to reproduce this and specify exact version of javac ?

**Comment by dimitris-athanasiou** [comment] 2016-02-25 18:41
I have created a sample maven project. The project simply contains a class called AlphaLambdaHolder which has to static lambda Suppliers. It also has an App class in the main of which a third lambda is created.

**Steps to reproduce**

- Get the zip file containing the project from [here](https://drive.google.com/folderview?id=0B4A6CmYZRXqNTDkwb0FYTnBmUWc&usp=sharing)
- Unzip the file into 2 separate directories (since the folder names play a role the ones I used was /Users/dimitris/lambda-enumeration and /Users/dimitris/what but I'm sure you can fiddle with the paths a bit to create the inconsistency. I got it on my first try.)
- Run "mvn  compile" in both directories
- Run "javap -v -p -s -c /Users/dimitris/lambda-enumeration/target/classes/com/jacoco/lambda/issue/App.class > app1.s"
- Run "javap -v -p -s -c /Users/dimitris/lambda-enumeration/target/classes/com/jacoco/lambda/issue/AlphaLambdaHolder.class > alphaLambdaHolder1.s"
- Run "javap -v -p -s -c /Users/dimitris/what/target/classes/com/jacoco/lambda/issue/App.class > app2.s"
- Run "javap -v -p -s -c /Users/dimitris/what/target/classes/com/jacoco/lambda/issue/AlphaLambdaHolder.class > alphaLambdaHolder2.s"
- Compare the files 

**Observed result**

Observe that in one of the alphaLambdaHolder files lambdas are with name "com/jacoco/lambda/issue/AlphaLambdaHolder.lambda$static$0" and "com/jacoco/lambda/issue/AlphaLambdaHolder.lambda$static$1" while in the other they are "com/jacoco/lambda/issue/AlphaLambdaHolder.lambda$static$1" and "com/jacoco/lambda/issue/AlphaLambdaHolder.lambda$static$2".

In the app files you have "com/jacoco/lambda/issue/App.lambda$main$2" or "com/jacoco/lambda/issue/App.lambda$main$0" respectively.

I hope this helps.

**Comment by dimitris-athanasiou** [comment] 2016-02-25 18:42
Forgot to mention versions for maven and jdk

Apache Maven 3.2.3 (33f8c3e1027c3ddde99d3cdebad2656a31e8fdf4; 2014-08-11T21:58:10+01:00)
Maven home: /usr/local/maven
Java version: 1.8.0_40, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_40.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.9.5", arch: "x86_64", family: "mac"

**Comment by Godin** [comment] 2016-02-25 20:23
@dimitris-athanasiou ok, I observe the difference, which you describe. It is interesting question - why this happens, however with ``App.main(new String[]{});`` in ``AppTest`` numbers in results are identical:

![selection_001](https://cloud.githubusercontent.com/assets/138671/13332769/f534e614-dc03-11e5-89da-39533aed2f39.png)

![selection_002](https://cloud.githubusercontent.com/assets/138671/13332774/f88a4e4e-dc03-11e5-92a8-40deabb3c42a.png)

of course there will be zeros, if I'll use "jacoco.exec" from one directory to generate report for classes compiled in another directory:
```
$ mvn -f lambda-enumeration org.jacoco:jacoco-maven-plugin:0.7.6.201602180812:prepare-agent clean test
$ cp lambda-enumeration/target/jacoco.exec what/target/jacoco.exec
$ mvn -f what compile org.jacoco:jacoco-maven-plugin:0.7.6.201602180812:report
...
[WARNING] Classes in bundle 'lambda-enumeration' do no match with execution data. For report generation the same class files must be used as at runtime.
[WARNING] Execution data for class com/jacoco/lambda/issue/AlphaLambdaHolder does not match.
[WARNING] Execution data for class com/jacoco/lambda/issue/App does not match.
```

Quoting [FAQ](http://eclemma.org/jacoco/trunk/doc/faq.html) :
> ### Why does a class show as not covered although it has been executed?
> ... Make sure you're using the exact same class file at runtime as for report generation. ...

@marchof do you have some ideas/thoughts about relaxation of this requirement?

**Comment by dimitris-athanasiou** [comment] 2016-02-25 20:51
I am glad you reproduced it cause it was driving me mad!

I understand that documentation already mentions the same class file requirement and technically what I report is not a bug. 

However, this is very restricting in terms of usage. It would demand that building/testing/sonar all happens in one big job which is executed in same directory.For instance, in my team we have different VMs running different steps in our continuous integration pipeline and I can imagine this is not an uncommon practice. Factoring in CI systems like Jenkins that always create a new directory for each build, it makes the issue unavoidable. 

I also understand that this is potentially an issue to report to JVM implementors as well as, in effect, java builds using lambdas are no longer repeatable. I mean, different byte-code just because the build was executed in different paths does not sound desirable.

With regard to solutions, wouldn't it be possible to preprocess the classes in order to remove the lambda id numbers?

**Comment by marchof** [comment] 2016-02-25 21:36
Hi, the classes of type "com.mycompany.MyClass$$Lambda$8/398572781" are created by the java runtime, not the java compiler. Although they become visible with the classdumpdir option they are not relevant for report generation.

For background information see this presentation: http://www.infoq.com/presentations/lambda-java8

**Comment by marchof** [comment] 2016-02-25 21:48
Regarding the example: Beside this is a quite interesting observation, JaCoCo by design works on class files. As cited from the FAQ JaCoCo relies on the fact that the same class files are used at runtime and at report generation time. A safe way to ensure this to actually use the same files and not rely on the assumption that javac will produce similar files in every run.

If for what ever reason javac decides to generate class files with different names in different runs JaCoCo cannot relate those.

**Comment by Godin** [comment] 2016-02-25 21:50
@marchof story is actually not about runtime , but about sugar generated by compiler - correct me if I'm wrong, but it looks like some sort of initialization :
![selection_001](https://cloud.githubusercontent.com/assets/138671/13335400/3e40a476-dc11-11e5-81b7-798a5ab4c43d.png)
![selection_002](https://cloud.githubusercontent.com/assets/138671/13335403/41cac9f0-dc11-11e5-8552-27bc3e2d1bbe.png)

```
private static java.lang.Integer lambda$static$1();
    descriptor: ()Ljava/lang/Integer;
    flags: ACC_PRIVATE, ACC_STATIC, ACC_SYNTHETIC
    Code:
      stack=1, locals=0, args_size=0
         0: iconst_1
         1: invokestatic  #2                  // Method java/lang/Integer.valueOf:(I)Ljava/lang/Integer;
         4: areturn
      LineNumberTable:
        line 7: 0
```

```
private static java.lang.String lambda$main$0();
    descriptor: ()Ljava/lang/String;
    flags: ACC_PRIVATE, ACC_STATIC, ACC_SYNTHETIC
    Code:
      stack=1, locals=0, args_size=0
         0: ldc           #8                  // String
         2: areturn
      LineNumberTable:
        line 14: 0
```

and names can vary - seems that depending on location of source files. And which results in difference of CRC64 checksum.

**Comment by marchof** [comment] 2016-02-25 21:57
@Godin Fully agree, I didn't realize that @dimitris-athanasiou 's comment was about the desugared lambda name as part of the dynamically generated classes.

I wonder whether this instability of the compiler should be asked at the OpenJDK project? I think many more tools will run in trouble with this.

**Comment by Godin** [comment] 2016-02-25 21:58
@marchof However I agree that reliance on same result of compilation is a bad idea in general. Question for OpenJDK guys is alredy in my todo-list ;)

@dimitris-athanasiou speaking about pipeline - it is highly arguable that each step of pipeline should re-compile code, because it may happen that integration tests (or whatever else) will check quality of something, while released will be something else. As an example - it can be really bad, if acidentially we executed tests on a binary in 1.8 format, but finally released with 1.9 format.

**Comment by dimitris-athanasiou** [comment] 2016-02-25 22:03
@Godin All steps in the pipeline work on exactly the same git SHA, same platform, same environment. It is just about better utilization of hardware.

**Comment by Godin** [comment] 2016-02-25 22:13
@dimitris-athanasiou Recompilation consumes hardware resources :smiley: But please don't get me wrong - I feel your pain about this checksum mismatch and will report this to OpenJDK. However rephrasing what @marchof said - not sure that on JaCoCo side we can do something about this in short term.

**Comment by Godin** [comment] 2016-02-25 22:15
@dimitris-athanasiou As an idea of workaround - you might try to find pattern for the names of directories which will guarantee the same result.

**Comment by dimitris-athanasiou** [comment] 2016-02-25 22:18
@Godin What about my idea for pre-processing the class files and removing the $<lambda_number> part before hashing them to create the class-id?

**Comment by marchof** [comment] 2016-02-25 22:23
@dimitris-athanasiou Nope. Class ids are generated on the plain binary representation of the class file. Any interpretation before class id generation will add a lot complexity.

Also it is not as simple as you think: It's not only about the name of the desugared method, the methods are also referenced in the call sites where the lambda is constructed. If we would remove $[lambda_number] everywhere we could not detect when there are actually different lambda bodies.

**Comment by dimitris-athanasiou** [comment] 2016-02-25 22:26
@marchof Fair enough. In that case it is really up to the OpenJDK guys. Thank you @Godin & @marchof for your help and to all of you bringing us Jacoco :-)

**Comment by dimitris-athanasiou** [comment] 2016-02-25 22:27
@Godin As I would like to follow up on the question to the OpenJDK guys, could you please post a link to the issue when you open it? I would appreciate it.

**Comment by marchof** [comment] 2016-02-25 22:28
@dimitris-athanasiou @Godin Thx for this pretty cool technical discussion! These are the kind of insights why I love to work on JaCoCo ;-)

**Closed** 2016-02-25 22:29 UTC

**Comment by dimitris-athanasiou** [comment] 2016-02-26 10:09
Guys, before you talk to OpenJDK you might want to check this out: [Lambda method names are unnecessarily unstable](https://bugs.openjdk.java.net/browse/JDK-8067422?jql=text%20~%20%22lambda%20name%22)

**Comment by Godin** [comment] 2016-02-26 10:21
@dimitris-athanasiou thank you for the link. Ticket says that it was resolved, but what we observe - it wasn't.

**Comment by dimitris-athanasiou** [comment] 2016-02-26 10:23
It is resolved in e.g., 8u40 b33. I tested on b25. I am going to retest on a build that's supposed to have the fix.

**Comment by dimitris-athanasiou** [comment] 2016-02-26 11:02
I retested with Oracle's 8u72 b15 - OpenJDK fix was backported to b01 - and I can confirm it works fine now. Enumeration of lambdas start over for each file. So it is "com/jacoco/lambda/issue/AlphaLambdaHolder.lambda$static$0", "com/jacoco/lambda/issue/AlphaLambdaHolder.lambda$static$1" and "com/jacoco/lambda/issue/App.lambda$main$0" regardless of which of the two directories I build.

**Comment by Godin** [comment] 2016-02-26 12:28
Cool :thumbsup: glad that this resolves your issue and thanks for notification.
