### ISSUE TITLE
java.nio.channels.OverlappingFileLockException for Jacoco offline

### ISSUE THREAD

**Issue by david-wei-wei** [jacoco/jacoco#331] opened 2015-07-09 15:03 UTC
Hi, recently I used Jacoco 0.7.2 to test our AppServer, Encountered such a problem:
```
java.nio.channels.OverlappingFileLockException 
at sun.nio.ch.SharedFileLockTable.checkList(FileLockTable.java:255) 
at sun.nio.ch.SharedFileLockTable.add(FileLockTable.java:152) 
at sun.nio.ch.FileChannelImpl.lock(FileChannelImpl.java:1030) 
at java.nio.channels.FileChannel.lock(FileChannel.java:1053) 
at org.jacoco.agent.rt.internal_e6e56f0.output.FileOutput.openFile(FileOutput.java:69) 
at org.jacoco.agent.rt.internal_e6e56f0.output.FileOutput.writeExecutionData(FileOutput.java:53) 
at org.jacoco.agent.rt.internal_e6e56f0.Agent.shutdown(Agent.java:137) 
at org.jacoco.agent.rt.internal_e6e56f0.Agent$1.run(Agent.java:54) 
```

In Jacoco Offline, are there different threads to synchronisation/write locking for jacoco.exec in one JVM? In order to avoid concurrent writes from different threads running in parallel in one JVM, I changed some code, it can solve our problem temporarily, as below:

```
private OutputStream openFile() throws IOException {
  final FileOutputStream file = new FileOutputStream(destFile, append);
  int retries = 5;//retries 5 times
  // Avoid concurrent writes from different agents running in parallel:
  for (int t = 0; t < retries; t++)
  try{
      file.getChannel().lock();
      break;
  }catch(OverlappingFileLockException ofe){
      System.out.println("[JACOCO][RT] Got OverlappingFileLockException, re-trying.");
      try {
                Thread.sleep(1000);
            } catch (InterruptedException e) {
                //ignore
            }
  }
  return file;
 }
```

Please help to check the issue.

**Comment by Godin** [comment] 2015-07-09 18:55
@david-wei-wei Quoting JavaDoc for OverlappingFileLockException - "Unchecked exception thrown when an attempt is made to acquire a lock on a region of a file that overlaps a region already locked by the same Java virtual machine". However in case of online instrumentation single JVM should have only single JaCoCo agent, and in case of offline instrumentation agent isn't needed and I suspect that indeed may interfere, so shouldn't be used. So could you please check those conditions?

**Comment by david-wei-wei** [comment] 2015-07-10 11:52
@Godin Thanks for your quick reply. 
When I tested some function for Weblogic Server, I instrumented all jars with offline model. When I shutdown Weblogic Server with following command, the exception will occur.
Running command and logs:

./stopWebLogic.sh
Stopping Weblogic Server...
/ade/user1_xx/bootstrap/java/1.8.0-40-25-150213.1.8.0.40.0025/jdk/bin/java -classpath /ade/user1_xx/bootstrap/java/1.8.0-40-25-150213.1.8.0.40.0025/jdk/lib/tools.jar:/scratch/user1/work/mw6775/wlserver/../oracle_common/modules/features/wlst.cam.classpath.jar:/scratch/user1/work/mw6775/wlserver/modules/features/wlst.wls.classpath.jar -Xms256m -Xmx512m -XX:CompileThreshold=8000   -Xverify:none -Djava.system.class.loader=com.oracle.classloader.weblogic.LaunchClassLoader -Djacoco-agent.output=file -Djacoco-agent.destfile=/ade/user1_xx/oracle/work/coverage/coverage.jacoco  -javaagent:/scratch/user1/work/mw6775/wlserver/server/lib/debugpatch-agent.jar -da -Dwls.home=/scratch/user1/work/mw6775/wlserver/server -Dweblogic.home=/scratch/user1/work/mw6775/wlserver/server   -Dweblogic.management.server=t3://xx:7004  weblogic.WLST shutdown-pwdchkServer.py

Initializing WebLogic Scripting Tool (WLST) ...

Welcome to WebLogic Server Administration Scripting Shell

Type help() for help on available commands

Connecting to t3://xx:7004 with userid weblogic ...

The EditMBeanServer is not enabled or not initialized
properly. This might happen if the EditMBeanServer is
disabled via the JMXMBean. Without this MBeanServer you
cannot make any configuration changes. Navigation to the
edit tree will be prohibited.

To view the root cause exception use dumpStack()
Successfully connected to Admin Server "pwdchkServer" that belongs to domain "custom_pwd_dom".

Warning: An insecure protocol was used to connect to the server.
To ensure on-the-wire security, the SSL port or Admin port should be used instead.

Shutting down the server pwdchkServer with force=false while connected to pwdchkServer ...
WLST lost connection to the WebLogic Server that you were connected to.
This may happen if the server was shut down or partitioned.
You will have to re-connect to the server once the server is available.
Disconnected from weblogic server: pwdchkServer
Disconnected from weblogic server:


Exiting WebLogic Scripting Tool.

java.nio.channels.OverlappingFileLockException
        at sun.nio.ch.SharedFileLockTable.checkList(FileLockTable.java:255)
        at sun.nio.ch.SharedFileLockTable.add(FileLockTable.java:152)
        at sun.nio.ch.FileChannelImpl.lock(FileChannelImpl.java:1030)
        at java.nio.channels.FileChannel.lock(FileChannel.java:1053)
        at org.jacoco.agent.rt.internal_e6e56f0.output.FileOutput.openFile(FileOutput.java:69)
        at org.jacoco.agent.rt.internal_e6e56f0.output.FileOutput.writeExecutionData(FileOutput.java:53)
        at org.jacoco.agent.rt.internal_e6e56f0.Agent.shutdown(Agent.java:137)
        at org.jacoco.agent.rt.internal_e6e56f0.Agent$1.run(Agent.java:54)
Done
Stopping Derby Server...

**Comment by marchof** [comment] 2015-07-11 16:31
It actually looks like there are two JaCoCo agents involved, maybe in two different versions (otherwise JaCoCo would detect this situation).

**Comment by marchof** [comment] 2015-07-11 16:32
So what would be interesting is the full command line of the running server process.

**Comment by david-wei-wei** [comment] 2015-07-12 14:41
@marchof 
My test process:
1. instrument all server jars with Jacoco offline
2. execute server startup
3. stop server later
The exception will occur during stopping the server.

full command line of server startup:
/ade/user1_xx/bootstrap/java/1.8.0-40-25-150213.1.8.0.40.0025/jdk/bin/java -server -ms160m -mx300m -Dweblogic.Name=pwdchkServer -Djava.security.policy=/scratch/user1/work/mw6775/wlserver/server/lib/weblogic.policy -Dweblogic.ProductionModeEnabled=true -server -ms160m -mx300m -Djava.security.properties==/ade/user1_xx/bootstrap/java/1.8.0-40-25-150213.1.8.0.40.0025/jdk/jre/lib/security/java.security -Dsecurity.overridePropertiesFile=false -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -Djava.security.egd=file:///dev/./urandom -Djava.endorsed.dirs=/scratch/user1/work/mw6775/wlserver/../oracle_common/modules/endorsed -Dplatform.home=/scratch/user1/work/mw6775/wlserver -Dweblogic.home=/scratch/user1/work/mw6775/wlserver/server -Dbea.home=/scratch/user1/work/mw6775/wlserver/.. -Dweblogic.management.username=weblogic -Dweblogic.management.password=welcome1 -Dweblogic.ListenPort=7004 -Djava.system.class.loader=com.oracle.classloader.weblogic.LaunchClassLoader -Djacoco-agent.output=file -Djacoco-agent.destfile=/ade/user1_xx/oracle/work/coverage/coverage.jacoco -javaagent:/scratch/user1/work/mw6775/wlserver/server/lib/debugpatch-agent.jar -da -Dwls.home=/scratch/user1/work/mw6775/wlserver/server -Dweblogic.home=/scratch/user1/work/mw6775/wlserver/server -Dweblogic.Stdout=/ade/user1_xx/oracle/work/TLR_TEST/resultout/functional/security/domains/custom_pwd_dom/pwdchkServer.out -Dweblogic.Stderr=/ade/user1_xx/oracle/work/TLR_TEST/resultout/functional/security/domains/custom_pwd_dom/pwdchkServer.err -Dweblogic.management.username=weblogic -Dweblogic.management.password=welcome1 weblogic.Server

full command line of server stopping:
/ade/user1_xx/bootstrap/java/1.8.0-40-25-150213.1.8.0.40.0025/jdk/bin/java -classpath /ade/user1_xx/bootstrap/java/1.8.0-40-25-150213.1.8.0.40.0025/jdk/lib/tools.jar:/scratch/user1/work/mw6775/wlserver/../oracle_common/modules/features/wlst.cam.classpath.jar:/scratch/user1/work/mw6775/wlserver/modules/features/wlst.wls.classpath.jar -Xms256m -Xmx512m -XX:CompileThreshold=8000 -Xverify:none -Djava.system.class.loader=com.oracle.classloader.weblogic.LaunchClassLoader -Djacoco-agent.output=file -Djacoco-agent.destfile=/ade/user1_xx/oracle/work/coverage/coverage.jacoco -javaagent:/scratch/user1/work/mw6775/wlserver/server/lib/debugpatch-agent.jar -da -Dwls.home=/scratch/user1/work/mw6775/wlserver/server -Dweblogic.home=/scratch/user1/work/mw6775/wlserver/server -Dweblogic.management.server=t3://xx:7004 weblogic.WLST shutdown-pwdchkServer.py

**Comment by Godin** [comment] 2015-07-20 09:12
@david-wei-wei As was said earlier - you don't need JaCoCo agent, if you use offline instrumentation. They both register shutdown hook and so interfere.

**Comment by david-wei-wei** [comment] 2015-07-20 09:32
@Godin  I remembered I did't use JaCoCo agent, I only set JaCoCo properties in Java Command: -Djacoco-agent.output=file -Djacoco-agent.destfile=/ade/user1_xx/oracle/work/coverage/coverage.jacoco. Could you help me to check it?

**Comment by Godin** [comment] 2015-07-20 09:37
@david-wei-wei I suspect that ``debugpatch-agent.jar`` is a patched JaCoCo agent, no?

**Comment by Godin** [comment] 2015-07-20 09:43
@david-wei-wei Another explanation could be that jar file ``org.jacoco:org.jacoco.agent:runtime``, which is used by offline-instrumented classes is loaded multiple times by different classloaders, causing multiple shutdown hooks. Which could easily be the case for application containers. I would even say that offline instrumentation is tricky to setup compared to online instrumentation with agent, so why not simply use online instrumentation?

**Comment by marchof** [comment] 2015-07-30 15:42
@david-wei-wei Any updates on this issue?

**Comment by evgen48** [comment] 2016-04-14 16:25
Hello, I've ram into exact that problem when creating eclipse RCP application, according to jacoco offline instrumentation, jacocoagent.jar should be in class path, since rcp uses own class loaders for different plugins, I had to add jacocoagent.jar both in classpath of junit tests, and in one of RCP module, and got described problem. Agent based instrumentation also not easily possibly for my project, dueto extensive usage of powermock. So I've tried proposed solution with cycle and several attempts to lock file, in my case there were only 1 collision,
`Results :

Tests run: 142, Failures: 0, Errors: 0, Skipped: 10

[JACOCO][RT] Got OverlappingFileLockException, re-trying.
[INFO] All tests passed!`

**Comment by Godin** [comment] 2016-05-25 20:02
@evgen48 could you please provide reproducer? this will greatly increase chances to re-open this ticket and finally make an official fix for it.

**Comment by marchof** [comment] 2016-05-25 20:23
@Godin For me the case of @evgen48 is obvious: If you put jacoco into multiple OSGi bundles you get different instances, as every bundle has its own classloader. I would close this ticked as invalid.

We might improve error reporting though: If there would be a reliable way to detect that we have more than one JaCoCo runtime in a JVM we could issue a proper error message.

**Comment by Godin** [comment] 2016-05-25 20:40
@marchof after careful rereading and your comment indeed case is obvious

And now I'm wondering: ok, offline instrumentation is required because of use of PowerMock, but what if it is combined with agent - I don't remember, if in this case it is still required to have `jacocoagent.jar` in class path? If not, then isn't it a solution? If yes, maybe we could make this possible as an improvement?

**Comment by marchof** [comment] 2016-05-25 21:00
@Godin Either add `jacocoagent.jar` to the classpath or configure the jar as an agent (which also ends on the classpath). In the latter configuration one has to set `excludes` property accordingly to avoid instrumentation of offline-instrumented classes.

**Comment by famod** [comment] 2020-06-05 22:47
FYI: Just stumbled upon this in Quarkus and created an issue there: https://github.com/quarkusio/quarkus/issues/9837

I doubt that Quarkus can/will work around all cases, so any improvement on your side (JaCoCo) is very much appreciated!

**Comment by marchof** [comment] 2020-06-08 11:29
@famod Thanks for the detailed analysis on the Quarkus issue! Do you have specific proposals what we can improve in the JaCoCo side in this situation?

**Comment by famod** [comment] 2020-06-08 15:07
> Do you have specific proposals what we can improve in the JaCoCo side in this situation?

Well, JaCoCo could just swallow the `OverlappingFileLockException`. But that might lead to a loss of coverage data, wouldn't it?
So I guess a retry could be helpful (similar to what @david-wei-wei posted originally).

**Comment by marchof** [comment] 2020-06-08 15:12
@famod Writing to the exec file without the lock will most likely result in a corrupted file. Some risks I see about the retry:

- Delaying JVM shutdown (wait) may cause other problems
- Still non-deterministic behavior

**Comment by famod** [comment] 2020-06-08 16:02
@marchof 

> Writing to the exec file without the lock will most likely result in a corrupted file.

To be clear, I am _not_ suggesting to write the file _without_ a lock. Each retry would need to (try to) acquire the lock.

> - Delaying JVM shutdown (wait) may cause other problems

Yes, this could happen but could be mitigated by using a deadline/timeout.

> - Still non-deterministic behavior

Yes, true. But due to lack of better (non-invasive) approaches...

**Comment by marchof** [comment] 2020-06-08 16:25
> Yes, true. But due to lack of better (non-invasive) approaches...

Well, there is a reliable setup: Do not deploy JaCoCo runtime multiple times on the same JVM :wink:

@famod From quarkusio/quarkus#9837 I assume you have a reproducer. As @Godin suggested we can give it a try and provide a pull request with the proposed workaround if you can re-test in your setup.

**Comment by famod** [comment] 2020-06-08 16:46
> Well, there is a reliable setup: Do not deploy JaCoCo runtime multiple times on the same JVM 

This seems almost impossible because it would deny frameworks like Quarkus the possibility to use "custom" classloaders, wouldn't it?

> @famod From [quarkusio/quarkus#9837](https://github.com/quarkusio/quarkus/issues/9837) I assume you have a reproducer. As @Godin suggested we can give it a try and provide a pull request with the proposed workaround if you can re-test in your setup.

You are more than welcome to do that and I will gladly re-test whatever you come up with (with some delay, my day job keeps me pretty busy).

**Comment by marchof** [comment] 2020-06-08 20:42
@famod Here is the version to for testing: https://ci.appveyor.com/project/JaCoCo/jacoco/builds/33396073/artifacts

**Comment by famod** [comment] 2020-06-09 10:38
@marchof Thanks, that was quick! Will test that later this week.

To be fair and transparent, me and my team have just decided to evaluate a possible _online_ solution first: https://github.com/quarkusio/quarkus/issues/9837#issuecomment-641195397

**Comment by famod** [comment] 2020-06-14 21:11
@marchof I am having a hard time getting the testing version to work properly in a Maven setup (https://github.com/famod/quarkus-issue-9837).
This was probably a bit naive:
```
mvn install:install-file -Dfile=jacocoagent.jar -DartifactId=org.jacoco.agent -DgoupId=org.jacoco -Dversion=0.8.6-SNAPSHOT -Dclassifier=runtime
```
as this yields:
```
[INFO] Running org.acme.testcoverage.GreetingServiceTest
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.017 s <<< FAILURE! - in org.acme.testcoverage.GreetingServiceTest
[ERROR] testGreetingService  Time elapsed: 0.01 s  <<< ERROR!
java.lang.NoClassDefFoundError: org/jacoco/agent/rt/internal_43f5073/Offline
        at org.acme.testcoverage.GreetingServiceTest.testGreetingService(GreetingServiceTest.java:10)
Caused by: java.lang.ClassNotFoundException: org.jacoco.agent.rt.internal_43f5073.Offline
        at org.acme.testcoverage.GreetingServiceTest.testGreetingService(GreetingServiceTest.java:10)
```

I guess the dedepencies of the Maven-Plugin are inconsistent (still on 0.8.5)?
There is one `jacocoagent.jar` in the zip (the other one is an OSGI-bundle). Which one is it? `runtime` or the "regular" one? And where is the other one?

Sorry for so many questions but I am a bit lost. Thanks!

**Comment by famod** [comment] 2020-06-17 08:02
@marchof ping, thanks!

**Comment by Godin** [comment] 2020-06-17 17:10
@famod 

> This was probably a bit naive
> I guess the dedepencies of the Maven-Plugin are inconsistent

yep, quoting https://www.jacoco.org/jacoco/trunk/doc/faq.html :

> #### Why do I get a NoClassDefFoundError or ClassNotFoundException for class org.jacoco.agent[...]Offline?
> If you use offline instrumentation the instrumented classes get a direct dependency on the JaCoCo runtime. Therefore jacocoagent.jar **of the same JaCoCo version** must be on the classpath and accessible from by the instrumented classes.

For the match between `org.jacoco:org.jacoco.core` (dependency of `jacoco-maven-plugin`) and `org.jacoco:org.jacoco.agent:runtime`

you can try either building from @marchof [branch](https://github.com/jacoco/jacoco/pull/1057):

```
git clone git@github.com:jacoco/jacoco.git --branch retry-execfile-lock
cd jacoco
mvn clean install
```

or try to update dependency of `jacoco-maven-plugin` - see https://maven.apache.org/guides/mini/guide-configuring-plugins.html#Using_the_dependencies_Tag

```
            <plugin>
                <groupId>org.jacoco</groupId>
                <artifactId>jacoco-maven-plugin</artifactId>
                <version>${jacoco.version}</version>
                <dependencies>
                    <dependency>
                        <groupId>org.jacoco</groupId>
                        <artifactId>org.jacoco.core</artifactId>
                        <version>0.8.6-SNAPSHOT</version>
                    </dependency>
                </dependencies>
```

after installing [artifacts](https://ci.appveyor.com/project/JaCoCo/jacoco/builds/33396073/artifacts) mentioned in https://github.com/jacoco/jacoco/issues/331#issuecomment-640875653

```
mvn install:install-file -Dfile=jacoco-0.8.6.202006080825/lib/jacocoagent.jar -DartifactId=org.jacoco.agent -DgoupId=org.jacoco -Dversion=0.8.6-SNAPSHOT -Dclassifier=runtime

mvn install:install-file -Dfile=jacoco-0.8.6.202006080825/lib/org.jacoco.core-0.8.6.202006080825.jar -DartifactId=org.jacoco.core -DgoupId=org.jacoco -Dversion=0.8.6-SNAPSHOT
```

> Which one is it? runtime or the "regular" one? And where is the other one?

Don't know what you mean by "it", "regular" and "other", but content of ZIP is described in documentation at https://www.jacoco.org/jacoco/trunk/index.html (`index.html` inside ZIP) and content of Maven repository described at https://www.jacoco.org/jacoco/trunk/doc/repo.html (`doc/repo.html` inside ZIP), so putting them together:

groupId | artifactId | classifier | inside ZIP | description |
-- | -- | -- | -- | --
org.jacoco | org.jacoco.agent | runtime | lib/jacocoagent.jar | Agent
org.jacoco | org.jacoco.agent | | lib/org.jacoco.agent-0.8.6.202006080825.jar | OSGi Bundle with API to get a local copy of the agent |
org.jacoco | jacoco-maven-plugin | | - | Plug-in for Maven |

**Comment by famod** [comment] 2020-06-17 21:12
@Godin Thanks a lot for this very detailed answer!

> Don't know what you mean by "it", "regular" and "other"

I was under the impression that there are _three_ `agent` flavours: the "regular" one (without classifier), the one with the `runtime` classifier and the OSGi one.

Again, thanks for this clarification!

I'll try building from the branch and will report back.

**Comment by famod** [comment] 2020-06-22 13:59
> I'll try building from the branch and will report back.

https://github.com/jacoco/jacoco/pull/1057#issuecomment-645632483

**Comment by nehmalho** [comment] 2020-07-21 06:52
hi @famod @godin did mvn install:install-file \
  -Dfile=jacoco-0.8.6.202006080825/lib/jacocoagent.jar \
  -DartifactId=org.jacoco.agent \
  -DgoupId=org.jacoco \
  -Dversion=0.8.6-SNAPSHOT \
  -Dclassifier=runtime

mvn install:install-file \
  -Dfile=jacoco-0.8.6.202006080825/lib/org.jacoco.core-0.8.6.202006080825.jar \
  -DartifactId=org.jacoco.core \
  -DgoupId=org.jacoco \
  -Dversion=0.8.6-SNAPSHOT

worked for lock exception issue. What is latest jacoco version we can use for same.

**Comment by nemalh** [comment] 2020-07-21 07:13
Hi @Godin @famod - is the error that is coming for lock exception resolved in this version of jacocco 0.8.6-Snapshot. Kindly update

**Comment by nemalh** [comment] 2020-07-21 07:22
Hi @Godin @famod - Is the lock exception issue fixed in above  version of jacoco kindly update

**Comment by Godin** [comment] 2020-07-21 07:25
@nemalh please stop spamming by creating and removing comments !

**Comment by nemalh** [comment] 2020-07-26 12:06
Hi, does java.nio.channels.OverlappingFileLockException
        at sun.nio.ch.SharedFileLockTable.checkList(FileLockTable.java:255)
        at sun.nio.ch.SharedFileLockTable.add(FileLockTable.java:152)
        at sun.nio.ch.FileChannelImpl.lock(FileChannelImpl.java:1062)
        at java.nio.channels.FileChannel.lock(FileChannel.java:1053)
        at org.jacoco.agent.rt.internal_8ff85ea.output.FileOutput.openFile(FileOutput.java:69)
        at org.jacoco.agent.rt.internal_8ff85ea.output.FileOutput.writeExecutionData(FileOutput.java:53)
        at org.jacoco.agent.rt.internal_8ff85ea.Agent.shutdown(Agent.java:137)
        at org.jacoco.agent.rt.internal_8ff85ea.Agent$1.run(Agent.java:54) 	

fixed with above 0.8.6 snapshot version if the same is tested kindly update

**Comment by famod** [comment] 2020-09-16 06:53
I must say it is rather disappointing that the fix for this is not included in the recently released 0.8.6. The PR is over 3 months old.

**Comment by marchof** [comment] 2020-09-16 09:49
@famod I apologies that this PR did not make it into the release. Please understand this is all spare time work. We prioritized the release because of experimental Java 15 and Java 16 support. Also we didn't want to do a "last minute merge". There will be a release soon, for official Java 15 support, so there is another chance to get this PR in.

**Comment by famod** [comment] 2020-09-16 11:49
@marchof ok, thanks for letting me know.

**Comment by xtaixe** [comment] 2020-10-13 18:06
Just a +1 on merging this and hopefully getting a release soon, since it's also affecting us and we tested with this branch and the fix works. Thanks.

**Comment by silviu-negoita** [comment] 2021-01-14 14:25
any updates on this? im waiting to be fixed

**Comment by xtaixe** [comment] 2021-06-29 07:28
@marchof I just realized today that there was another release and this still didn't make it. Just to set expectations, will this be merged at some point? Can we help in any way? Thanks.

**Comment by Godin** [comment] 2021-06-29 08:18
@xtaixe as far as we can see, in the meantime while we were on Java 16,  https://github.com/quarkusio/quarkus/issues/9837 was solved on Quarkus side by https://github.com/quarkusio/quarkus/pull/14311 Isn't it? Or in your case it is not about Quarkus?

**Comment by xtaixe** [comment] 2021-06-29 09:03
@Godin that comment mentions why it wasn't added in `0.8.6` but that the actual Java 15 - 16 release (`0.8.7`) would be an opportunity to get this in.

Our issue is with using Quarkus, but the Quarkus solution won't work for us cause it only works for a specific type of Quarkus tests (plus not sure if it works for Maven multi module projects).

So right now, we are running a patched JaCoCo jar to be able to get coverage properly, so it's going to be a pain to upgrade for every release this is not in... Since this seems to be ready and tested by some people, can it be prioritized now?

**Comment by Godin** [comment] 2021-06-29 09:42
> but that the actual Java 15 - 16 release (`0.8.7`) would be an opportunity to get this in.

As was already said - we saw resolution of corresponding ticket on Quarkus side, but till now no mention of

> the Quarkus solution won't work for us cause it only works for a specific type of Quarkus tests

maybe I miss something, but don't see any example of this or any mentions of this anywhere on Quarkus side, while IMO this is valuable information - maybe Quarkus developers can already suggest something for your type of tests or do further improvements, or improve documentation/examples by mentioning known limitations. Anyway thank you for sharing/mentioning this at least here now 👍 

Also yes sorry that this opportunity and ticket were overlooked in `0.8.7` - there were many things to do for Kotlin `1.5` and far less spare time.

> Since this seems to be ready and tested by some people, can it be prioritized now?

Yes and thank you for the reminder, explanations and testing.

**Comment by xtaixe** [comment] 2021-06-29 11:19
Cool. Thanks! Sorry, I see now I didn't understand your first comment about priority properly and you are right it should have been mentioned the Quarkus solution has some caveats... In case it helps or just FYI the Quarkus limitation and suggestion to fallback to the normal plugin is explained here: https://quarkus.io/guides/tests-with-coverage#coverage-for-tests-not-using-quarkustest

Can't wait for the next release! Thanks again.

**Comment by famod** [comment] 2021-06-29 11:58
@xtaixe I must say the combination of the `quarkus-jacoco` extension plus the `jacoco-maven-plugin` (as described by the article you've linked to) works rather well for us.
Which cases don't work for you?

**Comment by xtaixe** [comment] 2021-06-29 13:01
Honestly, I missed that the fallback is supposed to be used in combination with the extension and not as replacement (with the same configuration as before) 🤦🏻... So it's using online instrumentation now, right? @famod if you can confirm everything works also for multi module projects I might try to give it a go and report back IF I find time cause it's not going to be a quick change since we have different reports for different types of tests, so our configuration is a bit complex and relying on offline instrumentation right now...

**Comment by famod** [comment] 2021-06-29 13:34
@xtaixe It's all "online" which I consider a big plus.
Multi module should work as well. The Quarkus extension is even merging everything, AFAIK.
How well that merge works with non-Quarkus tests I cannot say yet (we are currently splitting our main backend into modules).

**Comment by xtaixe** [comment] 2021-06-29 14:16
I started reviewing our config and things are starting to come back to me (it was hard getting everything working)... For the end to end tests we do (and they they need to be setup) we are still going to need offline instrumentation, so if the maintainers are ok with it, getting this issue fixed in JaCoCo is still the best solution for us to be able to keep the configuration the same for our different coverage reports (just changing a maven profile with some properties), otherwise it's going to get crazy to get every thing working differently in a big-ish multi module project...

**Comment by xtaixe** [comment] 2021-09-20 09:31
Just FYI, not all cases currently work on Quarkus: https://github.com/quarkusio/quarkus/issues/18559. So hopefully this can still be prioritized... Thanks.

**Comment by eformat** [comment] 2021-12-16 02:25
+1 to getting this merged. i have been following it for a while.

I have a similiar test case that is fixed with this PR i.e.

using jacoco version 0.8.7 - gives 0% code coverage
using 0.8.8-SNAPSHOT (which has this PR) works OK

Code is here (mvn test) ..
https://github.com/petbattle/pet-battle-api/blob/master/pom.xml

**Closed** 2022-04-04 21:52 UTC
Labels: type: enhancement, component: core

**Comment by xtaixe** [comment] 2022-04-05 12:44
Thanks!
