### ISSUE TITLE
Plugin Maven 4 Compatibility

### ISSUE THREAD

**Issue by mikerimov** [jacoco/jacoco#1497] opened 2023-07-17 19:40 UTC
* JaCoCo version: 3.10.0
* Operating system: OS X 13.4.1
* Tool integration: Maven
* Maven 3.9.2 is emitting the following warnings about `jacoco-maven-plugin` expressing dire warnings when maven 4 is released

Maven Output:
```
[WARNING] Plugin validation issues were detected in 1 plugin(s)
[WARNING] 
[WARNING]  * org.jacoco:jacoco-maven-plugin:0.8.10
```
*snip for brevity*
```
[WARNING]   Plugin issue(s):
[WARNING]    * Plugin is a Maven 2.x plugin, which will be not supported in Maven 4.x
[WARNING]    * Plugin mixes multiple Maven versions: [3.0, 2.0.2]
[WARNING]    * Plugin should declare these Maven artifacts in `provided` scope: [org.apache.maven:maven-repository-metadata:3.0, org.apache.maven:maven-artifact:3.0]
[WARNING]    * Plugin depends on plexus-container-default, which is EOL
```

Since jacoco-maven-plugin docs clearly state that maven 3 is required, I don't see any reason you couldn't begin pruning the maven2 required bits now rather than waiting for the bugs to come in later.

Replication.  Extract the following pom.xml zip (simple file) and run  `mvn install -Dmaven.plugin.validation=VERBOSE`

[pom.xml.zip](https://github.com/jacoco/jacoco/files/12073282/pom.xml.zip)

**Comment by Godin** [comment] 2023-07-17 19:41
Duplicate of https://github.com/jacoco/jacoco/issues/1435

**Closed by Godin** 2023-07-17 19:41 UTC
Labels: type: enhancement
