### ISSUE TITLE
Coverage dropped from 33 to 26% with 0.7.3

### ISSUE THREAD

**Issue by paulwellnerbou** [jacoco/jacoco#294] opened 2015-03-06 14:54 UTC
We have a quite complex and big multi module maven java project, we are using the maven jacoco plugin for test coverage analysis as described here (http://docs.sonarqube.org/display/SONAR/Code+Coverage+by+Unit+Tests+for+Java+Project):

Pre-Build-Step: ```mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install -Dmaven.test.failure.ignore=true```

After that, we run the jenkins Sonar plugin (which is, as far as I know, a ```mvn sonar:sonar```).

We had a coverage of about 33%. On February, 20, this coverage dropped to about 26%. We had no code changes on this day. As this was the day of the 0.7.3 release, I tried again with the 0.7.2 and the coverage is back to 33%,

Any idea why this could happen? Or how we can debug this and lookt into it?

The project itself does not seem to be the problem, we have a smaller one on github which shows different coverage numbers between 0.7.4/3 and 0.7.2 as well: https://github.com/faz-electronic-media/query

**Comment by marchof** [comment] 2015-03-06 15:25
We have a known regression in 0.7.3 (#286) which should be fixed in 0.7.4.

Can you please drill down reports created with 0.7.2 and 0.7.4 to identify specific differences e.g. on source file level?

**Comment by bluejuh** [comment] 2015-03-07 01:32
I can confirm that we are seeing a similar drop in code coverage between 0.7.2 and 0.7.4. Unlike the example above, we were unable to use 0.7.3 due to the ArrayIndexOutOfBoundsException seen in #285. That exception was fixed in 0.7.4, but this coverage drop remains.

Can you elaborate on what info I can supply from our reports to help debug this issue?

**Comment by marchof** [comment] 2015-03-07 07:12
@bluejuh As said above: If you could please drill down both reports to a specific piece of code where you can see a difference. A screenshot would be very helpful.

**Comment by paulwellnerbou** [comment] 2015-03-09 11:17
I noticed those Exceptions as well. They are gone in 0.7.4, but that is not fixing the coverage problem.

I tried to drill it down in the mentioned project (https://github.com/faz-electronic-media/query). It is the PowerMock-Test which is causing different coverage (TimeStateWithPreviewTimeFilterTest.java).

Are there any JaCoCo/Powermock version conflicts? We are using Powermock 1.5.1 with mockito in this case.

**Comment by marchof** [comment] 2015-03-09 13:50
It is a known lomitation that JaCoCo does not work well with Powermock or other mocking frameworks which modify the classes under test.

Question: So you didn't change anything except upgrading JaCoCo from 0.7.2 to 0.7.4 and the coverage droped for those tests using Powermock?

**Comment by paulwellnerbou** [comment] 2015-03-09 14:42
No, we did not change anything.
I reproduced the issue using the project on github mentioned above, same codebase, same maven command, just changing the jacoco version.

**Comment by Godin** [comment] 2015-03-09 16:09
@paulwellnerbou given project can't be used by us as reproducer, because it lacks dependencies - "mvn clean install" gives:
```
Could not find artifact com.polopoly:polopoly:jar:api:10.6.1-fp11-c871a5b in central
```

**Comment by paulwellnerbou** [comment] 2015-03-09 16:49
@Godin I know, you need polopoly access for it. But I assume you can reproduce it with any PowerMock test. I wil try to find the time to create a project to reproduce it.

**Comment by marchof** [comment] 2015-03-09 16:53
I'm pretty sure this is also related to #272. Probably some Powermock modified classes do not specify a proper source location.

**Comment by Godin** [comment] 2015-03-09 16:54
@marchof same feeling on my side

**Comment by rliesenfeld** [comment] 2015-03-09 17:24
Indeed, this is probably caused by the fix for #272, which excluded classes without a source location from coverage measurement. If this is really the case (and it appears so), I would say that the fix for #272 is correct, and the true problem lies in PowerMock.

Probably, the custom class loader with which PowerMock creates copies of classes (as specified through `@PrepareForTest(SomeClass.class)`), is not replicating the `ProtectionDomain` of the original class; maybe it leaves the protection domain null.

If that's the case, then the solution would be for PowerMock to simply copy the `ProtectionDomain` when creating each "prepared for test" class.

**Comment by rliesenfeld** [comment] 2015-03-09 18:35
I verified the cause of the problem is indeed as described in the previous comment. PowerMock's `MockClassLoader` calls `ClassLoader#defineClass` without a ProtectionDomain, resulting in the default JVM PD being used, which has a CodeSource with a null location.

I opened an issue in the PowerMock issue tracker: https://code.google.com/p/powermock/issues/detail?id=544

**Comment by Godin** [comment] 2015-03-09 18:37
@rliesenfeld Cool, thanks!

**Comment by marchof** [comment] 2015-03-27 05:06
So in this case there is no action on our side.

**Closed by marchof** 2015-03-27 05:06 UTC
Labels: otherproject

**Comment by bluejuh** [comment] 2015-07-07 18:45
Is there a workaround in place for this issue?

I understand the cause of the problem lies with PowerMock, but our builds are still frozen at jacoco 0.7.2 until this incompatibility is resolved.

**Comment by Godin** [comment] 2015-07-07 18:52
@bluejuh It is unclear what you expect from JaCoCo, since issue in Powermock?

**Comment by bluejuh** [comment] 2015-07-07 19:16
To clarify: Do we have a known workaround for the issue between PowerMock and JaCoCo that was discussed above, or is PowerMock considered "unsupported" by JaCoCo until the cause is fixed on their end?

It seems that the only workarounds at the moment are:
 * Use a tool other than PowerMock
 * Use a tool other than JaCoCo
 * Pin builds to use JaCoCo 0.7.2

We chose to stay with JaCoCo 0.7.2 as a short-term fix four months ago, but I was hoping there was some progress (if not a code-fix within JaCoCo, then perhaps a config or environment change in our system) to get these tools working together.

**Comment by Godin** [comment] 2015-07-07 19:24
@bluejuh I suspect that offline instrumentation might help. Could you please try?
