### ISSUE TITLE
Allow changing source folders via Maven plugin to support multi release JAR projects

### ISSUE THREAD

**Issue by pmwmedia** [jacoco/jacoco#1085] opened 2020-08-20 17:13 UTC
### Scenario

* JaCoCo version: 0.8.5.201910111838
* Operating system: Windows 10
* Tool integration: Maven
* Description of your use case:

I have a multi release JAR project and run surefire tests with Java 8 and failsafe tests with Java 9 or later. In my use case, the surefire tests run all JUnit tests and JaCoCo can generate a report for all of them perfectly. However, failsafe reruns JUnit tests for classes for which I have a separate implementation for Java 9+ (folder `META-INF/version/9` in the JAR). The problem is that JaCoCo cannot map these classes to the right source files. Unfortunately, the Maven plugin for JaCoCo does not allow to customize the directories for source files. It would be nice to be allowed to add additional source folders or to override the automatically considered source folders.

### Current Behaviour

Currently, there is no possibility to customize the directories, in which JaCoCO should look for source files, via Maven, In my use case, I get these warnings:

```
Classes in bundle 'tinylog-core' do no match with execution data. For report generation the same class files must be used as at runtime.
Execution data for class org/tinylog/core/runtime/JavaClassNameBasedStackTraceLocation does not match.
Execution data for class org/tinylog/core/runtime/JavaIndexBasedStackTraceLocation does not match.
```

### Wanted Behaviour

Configuration properties for the Maven plugin to customize the directories for source files. It should be possible to add additional source folders or to override the automatically considered source folders.

### Possible Workarounds

Haven't found any workaround, yet. Any ideas for a workaround are welcome :)

**Comment by Godin** [comment] 2020-08-20 18:38
Closing as duplicate of #965 , for the workaround see https://github.com/jacoco/jacoco/issues/965#issuecomment-545207685 that points to https://github.com/amaembo/streamex/pull/203

**Closed by Godin** 2020-08-20 18:38 UTC
Labels: type: enhancement

**Comment by pmwmedia** [comment] 2020-08-20 18:52
@Godin Thanks for the example amaembo/streamex#203. It really helps me!
