### ISSUE TITLE
Jacoco creates assets under a hidden folder for most HTTP web servers

### ISSUE THREAD

**Issue by marodriguez-llbean** [jacoco/jacoco#435] opened 2016-07-28 15:03 UTC
We are using the jacoco/gradle plugin to generate the code coverage report and exposing it in a local/internal web server, however, all images/CSS/JS files are created under ".resources" folder.  By default most HTTP servers handle files/folders beginning with period as hidden, requiring to explicitly expose hidden files in order to expose the code coverage report properly.

### Steps to reproduce

JaCoCo version:  JaCoCo 0.7.1.201405082137
Operating system:  windows
Tool integration: Gradle

### Expected behaviour
Rename ".resources" folder to something without leading period.

### Actual behaviour
images/CSS/JS files created under ".resources" folder.

**Comment by Godin** [comment] 2016-07-28 15:36
Closed as duplicate of #401 , which was fixed in version 0.7.7

**Closed by Godin** 2016-07-28 15:36 UTC
