### ISSUE TITLE
Instrumented inline functions in different modules cannot be executed

### ISSUE THREAD

**Issue by realdadfish** [jacoco/jacoco#786] opened 2018-11-09 08:23 UTC
I have a reified inline function declared in a base Gradle module `base`, something like this:

    inline fun <reified T> Fragment.findCallback(): T = when {
        parentFragment is T -> parentFragment as T
        targetFragment is T -> targetFragment as T
        context is T -> context as T
        else -> throw IllegalStateException("Neither parent, target or context implement " + T::class.java)
    }

Now, when this code in a  `feature` module, I receive a crash on runtime:

    java.lang.IllegalAccessError: tried to access method my.base.module.FragmentExt.$jacocoInit()[Z 
        from class my.feature.module.AlertDialogFragment
            at my.feature.module.AlertDialogFragment.onAttach(AlertDialogFragment.kt:27)

I'm aware that Jacoco has limited support for inline functions in Kotlin and while some of the issues, but while I can easily remove `inline` from some of my utilities, reified functions really need to be inlined, otherwise I cannot access the caller type.

### Versions

JaCoCo version: 0.8.2
Operating system: macOS 10.13
Tool integration: Android Gradle Plugin 3.2.0

**Comment by Godin** [comment] 2018-11-09 12:49
Duplicate of #688 that goes down to https://issuetracker.google.com/issues/109771903 :

Even in absence of complete example, I'm pretty sure that problem is in Android tooling: instrumentation must be done after inlining, i.e. compilation of `feature.module` must not use instrumented classes of `feature.module`.

**Closed by Godin** 2018-11-09 12:49 UTC
