### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException  while creating report [javac]

### ISSUE THREAD

**Issue by teyssieuman** [jacoco/jacoco#585] opened 2017-08-30 18:23 UTC
### Steps to reproduce

> ant  TcTSBool -v

JaCoCo version: 0.7.8 or 0.7.9 (no difference)
Operating system: Linux CentOS 6
Tool integration:  ANT

### Expected behaviour

The report generation should be a success

### Actual behaviour

BUILD FAILED (the jacoco report generation fails)
[testGen.tar.gz](https://github.com/jacoco/jacoco/files/1264637/testGen.tar.gz)

**Comment by Godin** [comment] 2017-08-30 20:19
@teyssieuman first of all - thank you for this report with reproducer! :thumbsup:

This looks very similar to a bug in `javac` that we already reported to OpenJDK - [JDK-8144185](https://bugs.openjdk.java.net/browse/JDK-8144185).

Here is part of decompiled `bin/operators/And.class` :
```
  public operators.Operator nextMutant() throws operators.OperatorMutationException;
    descriptor: ()Loperators/Operator;
    flags: ACC_PUBLIC, ACC_BRIDGE, ACC_SYNTHETIC
    Code:
      stack=1, locals=1, args_size=1
         0: aload_0
         1: invokespecial #60                 // Method operators/AbstractOperator.nextMutant:()Loperators/Operator;
         4: areturn
      LineNumberTable:
        line 17: 0
      LocalVariableTable:
        Start  Length  Slot  Name   Signature
            0       5     0  this   Loperators/And;
      RuntimeInvisibleTypeAnnotations:
        0: #73(): LOCAL_VARIABLE, {start_pc=65, length=27, index=3}
    Exceptions:
      throws operators.OperatorMutationException
```

This synthetic bridge method generated by `javac` contains `RuntimeInvisibleTypeAnnotation` whose `start_pc` exceeds size of a method. And this causes `ArrayIndexOutOfBoundsException` in ASM library that we use.

Reduced example:
```
abstract class A {
  @java.lang.annotation.Target({ java.lang.annotation.ElementType.TYPE_USE })
  public @interface Annotation {
  }

  public Object fun() {
    @Annotation
    Object x = null;
    System.out.println();
    return x;
  }
}

public class C extends A {
}
```

Workarounds:
* exclude class `operators/And` from coverage analysis
* remove `@NonNull` annotation from method `operators/AbstractOperator#nextMutant()`
* avoid generation of bridge method, e.g. by changing visibility of class `operators/AbstractOperator` from package-private to public

Not sure if there is a way to implement workaround on our side.

**Comment by teyssieuman** [comment] 2017-08-31 11:43
@Godin : Thank you for this rapid and precise answer.
Concerning the workarounds:

- Removing the `@NonNull` annotation do not seem to have a positive effect (the problem still occur).
- Same for changing the visibility of the abstract class from package-private to public.
- Using the ECL still an option that i do not test yet.
- Excluding the And can be done, but I also have to exclude a lot of class where this similar construction is present.

You mentioned à problem that have been reposted on OpenJDK. 
(Pardon me if I say nonsense, but I tried using the Oracle JDK, and I still have the same problem.)

The problem on the OpenJDK is declared to be solved since 2017-06-19.
Is the correction made on the OpenJDK really solve this issue ?

**Comment by Godin** [comment] 2017-08-31 18:22
@teyssieuman 

> Removing the `@NonNull` annotation do not seem to have a positive effect (the problem still occur)

For the given example this perfectly works for me as following:

```
$ javac -version
javac 1.8.0_131

$ java -version
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

$ wget --quiet https://github.com/jacoco/jacoco/files/1264637/testGen.tar.gz

$ aunpack --quiet testGen.tar.gz
testGen.tar.gz: extracted to `testGen'

$ cd testGen

$ cat ../p.patch
```
```diff
--- src/operators/AbstractOperator.java
+++ src/operators/AbstractOperator.java
@@ -88,7 +88,7 @@ abstract class AbstractOperator implements Operator {
 				if(mutant==null) {
 					continue;
 				}else {
-					@NonNull
+//					@NonNull
 					final List<Operator> mutInputs = new ArrayList<>(inputs);
 					mutInputs.set(i, mutant);
 					try {
```
```
$ patch -p0 ../p.patch

$ ant clean build-project TcTSBool
Buildfile: /private/tmp/jacoco/testGen/build.xml

clean:

init:
    [mkdir] Created dir: /private/tmp/jacoco/testGen/bin

build-project:
     [echo] testGen: /private/tmp/jacoco/testGen/build.xml
    [javac] Compiling 56 source files to /private/tmp/jacoco/testGen/bin

TcTSBool:
    [junit] Running tests.TcTSBool
    [junit] Tests run: 11, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.472 sec
[jacoco:coverage] Enhancing junit with coverage
    [junit] objc[12109]: Class JavaLaunchHelper is implemented in both /Users/evgeny.mandrikov/.java-select/versions/jdk8u131/jre/bin/java and /Users/evgeny.mandrikov/.java-select/versions/jdk8u131/jre/lib/libinstrument.dylib. One of the two will be used. Which one is undefined.
    [junit] Running tests.TcTSBool
    [junit] Tests run: 11, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.093 sec
[jacoco:merge] Loading execution data file /private/tmp/jacoco/testGen/jacoco.exec
[jacoco:merge] Loading execution data file /private/tmp/jacoco/testGen/merged.exec
[jacoco:merge] Writing merged execution data to /private/tmp/jacoco/testGen/merged.exec
[jacoco:report] Loading execution data file /private/tmp/jacoco/testGen/merged.exec
[jacoco:report] Writing bundle 'testGen' with 55 classes

BUILD SUCCESSFUL
Total time: 3 seconds
```

> Excluding the And can be done, but I also have to exclude a lot of class where this similar construction is present.

We do our best to test various JDK versions and be compatible, but please understand that not easy and not always possible to implement workarounds for bugs in third-party components, especially in compiler and taking into account that JaCoCo is developed by volunteers in their spare time (between work and personal lives, at nights, weekends, etc) absolutely for free. 

AFAIK since discovery of this bug in 2015, we've never received reports similar to yours and hence wasn't even aware of any impacts. At the moment I can only apologize for OpenJDK developers. But as you can see - kept this ticket open on our side to check what we can do or maybe receive as contribution.

> You mentioned à problem that have been reposted on OpenJDK.
(Pardon me if I say nonsense, but I tried using the Oracle JDK, and I still have the same problem.)

You can consider OpenJDK as open-source part of OracleJDK, and OracleJDK as custom build of OpenJDK done by Oracle - they share a lot, including bug tracker, developers/contributors, etc. And in particular code of `javac` compiler.

> The problem on the OpenJDK is declared to be solved since 2017-06-19.

Notice that commit was done only into JDK 10 and as of today there is no associated tickets to do backports.

> Is the correction made on the OpenJDK really solve this issue ?

Don't know yet for sure. We are not always receiving notifications about fixes of the issues that we report, and this one was created at 2015-10-24 (a long time ago to my taste), which is even before we started receiving some notifications (before joined OpenJDK Quality Outreach program, even before its creation) and before we started addition of tests into JaCoCo codebase targeting OpenJDK bugs.

Looking on comments in bug report and associated patch, seems very likely.

Check - is definitely a good idea. And we do appreciate contributions whether it is simply such check and comment, or addition of test, or fix.

Thank you for your understanding.

**Comment by Godin** [comment] 2017-09-06 19:15
For the record link to a discussion in ASM library about this: 
http://forge.ow2.org/tracker/?func=detail&aid=317789&group_id=23&atid=100023

**Comment by Godin** [comment] 2018-01-31 16:07
For the record: fix was backported to JDK 8u172 - https://bugs.openjdk.java.net/browse/JDK-8191969

**Comment by turbanoff** [comment] 2018-06-16 05:10
@Godin is it really was included in 8u172? Can't find info about this bug in bugfixes pages
http://www.oracle.com/technetwork/java/javase/2col/8u171-bugfixes-4308891.html
http://www.oracle.com/technetwork/java/javase/2col/8u172-bugfixes-4308894.html

**Comment by NicklasWallgren** [comment] 2019-04-16 13:29
I'm encountering this issue using Java 11. Are there any known workarounds, or aren't we able to use Jacoco with `@NonNull`.

**Comment by Godin** [comment] 2019-04-16 18:03
@NicklasWallgren as already well-described in the comments above:

> I'm encountering this issue using Java 11.

Issue described here is not about Java Runtime Environment, but about invalid `class` files coming from a bug in Java compiler. As far as we know this has been fixed in JDK 10 and therefore Java compiler version 10 and greater does not produce invalid `class` files.

> Are there any known workarounds, or aren't we able to use Jacoco with `@NonNull`.

JaCoCo requires valid `class` files - exact same examples from https://github.com/jacoco/jacoco/issues/585#issuecomment-326107056 and https://github.com/jacoco/jacoco/issues/585#issue-254092348 work perfectly fine when compiled with

```
$ javac -version
javac 11.0.1
```

Therefore
* either your `class` files was not produced by proper compiler version - please recompile,
* or this is not about your `class` files (e.g. dependencies) - upgrade them or they can be excluded from JaCoCo instrumentation and analysis,
* or you face completely different issue - please provide complete reproducer.

**Closed** 2020-11-08 19:54 UTC
Labels: component: core, declined: otherproject :alien:
