### ISSUE TITLE
class variable show uncovered, but the variable has been reference in method and show covered

### ISSUE THREAD

**Issue by WilliamHu126** [jacoco/jacoco#712] opened 2018-07-17 03:19 UTC
This is a issue tracker. Please use our mailing list for general questions: 
https://groups.google.com/forum/?fromgroups=#!forum/jacoco

Also check FAQ before opening an issue: http://www.jacoco.org/jacoco/trunk/doc/faq.html

### Steps to reproduce

JaCoCo version:0.8.1
Operating system:centos6.5
Tool integration: Maven

### Expected behaviour
class 'logger' static variable show covered when the class method has been called.

### Actual behaviour
show uncovered

![_15314686603491](https://user-images.githubusercontent.com/25794477/42794750-326e2522-89b3-11e8-9fc3-4a6c7b86f11a.png)

**Comment by marchof** [comment] 2018-07-17 07:08
@WilliamHu126 The report does not look like a native JaCoCo Report. What tool are you using here? Please not that we can only support the tools which we provide with JaCoCo. Can you please test with JaCoCo's Maven goal `report`?

If the problem is also with our report please provide a standalone reproducer (preferrably a Github repo)  so we can debug this issue.

**Comment by WilliamHu126** [comment] 2018-07-25 09:19
OK，I will paste the report later....

**Comment by WilliamHu126** [comment] 2018-08-01 11:00
@marchof I have get the native html report according to cli, it also the same as my report. please check the below attach, I'm sure provide some information of server data. Could you give me some clue to shoot the root cause?
![image](https://user-images.githubusercontent.com/25794477/43517627-fb61cd30-95bb-11e8-86be-cd6755f9f3ff.png)
![image](https://user-images.githubusercontent.com/25794477/43517886-c7dce6b0-95bc-11e8-9fd6-ee0fb0a3469d.png)
![image](https://user-images.githubusercontent.com/25794477/43517957-02c9b0a0-95bd-11e8-9953-2253e99a933b.png)

**Comment by WilliamHu126** [comment] 2018-08-01 11:11
@marchof In addition below attach is the maven setting which dump jacoco data from server in pom.xml
![image](https://user-images.githubusercontent.com/25794477/43518315-45fc6f06-95be-11e8-9766-7240a627622d.png)

**Comment by marchof** [comment] 2018-08-01 11:15
@WilliamHu126 Thanks for the additional information! First of all, the logger is a non-static and therefore initialized when a instance is created. As you are calling non-static methods someone obviously created the instance.

What also looks strange is that also the class declaration line is red. Typically the default constructor is assigned to this line. So it looks like execution of the constructor is not recorded or there was a remote reset after the class has been created.

What is the runtime you're executing the code in?

**Comment by marchof** [comment] 2018-08-01 12:02
Could be. The only chance to follow this up if you could provide an isolated reproducer, which we can launch. Preferable a Github repo.

**Comment by WilliamHu126** [comment] 2018-08-01 15:29
@marchof I just have a question, jacocoagent will insert detect probe before main start, why not catch spring initialize java class action? About reproducer I need to try again

**Comment by marchof** [comment] 2018-08-01 15:57
@WilliamHu126 Probes are inserted by the agent when a class is loaded. This means before static initialization and instantiation. I have no idea how this can happen what you see without debugging it on a reproducer.

**Comment by marchof** [comment] 2018-08-01 15:58
@WilliamHu126 Just to double check: This will happen when someone requested a dump from the JaCoCo agent with reset=false. Are you sure the Maven snipped shown above is the the only interaction with the agent?

**Comment by Godin** [comment] 2018-08-01 17:39
I have feeling that instead @marchof made a typo and instead

> This will happen when someone requested a dump from the JaCoCo agent with reset=false

wanted to say "reset=true".

Another assumption, wild guess in absence of reproducer and experience with springframework: if instance of this class is created by springframework, then could it be that springframework simply skips constructor of this class and injects some logger by setting value to the field despite your initialization? To investigate:
what happens if you add explicit empty public constructor
```
public QueryBindWechatBuss() {
}
```
? what happens if you completely remove initialization of this field, i.e. remove
```
= LoggerFactory.getLogger(this.getClass())
```
? what happens if initialization is in constructor
```
private Logger logger;

public QueryBindWechatBuss() {
  logger = LoggerFactory.getLogger(this.getClass())
}
```
? what happens if you put breakpoint and run under debugger?

**Comment by marchof** [comment] 2018-08-01 17:44
@WilliamHu126 Sorry, made a typo in my previous comment: `reset=true` would remove the execution data from initialization.

**Comment by WilliamHu126** [comment] 2018-08-04 06:16
@Godin @marchof Thank you for your comments. the root cause is the 'reset=true' indeed. I did clear coverage action when TA execution.

**Comment by marchof** [comment] 2018-08-05 15:41
@WilliamHu126 Glad you found it! Closing -> works as designed.

**Closed by marchof** 2018-08-05 15:41 UTC
Labels: declined: invalid
