### ISSUE TITLE
Kotlin sealed classes or data classes not being covered correctly

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [jacoco/jacoco#1044] opened 2020-04-05 14:56 UTC
<img width="1135" alt="image" src="https://user-images.githubusercontent.com/7463564/78501847-01db4580-775e-11ea-8f67-bd22e183080b.png">

All those data classes are covered with the same number of tests, but if they are in one line, they are marked as not tested.

I think it is caused because `headers` are not being covered al 100%. But I don't know if Jacoco counts that every data class is not being tested or only the header part.

You can see all tests and the Gradle config here: https://github.com/JavierSegoviaCordoba/NetworkResponse

**Comment by Godin** [comment] 2020-04-07 08:29
The provided screenshot is not HTML report generated by JaCoCo.

`gradle test jacocoTestReport`
after enablement of JaCoCo HTML report
on top of https://github.com/JavierSegoviaCordoba/NetworkResponse/commit/50a69d8e517223f1c762a216e26c5e09da62ac25

```diff
diff --git i/networkResponse/build.gradle.kts w/networkResponse/build.gradle.kts
index 601bd1b..ed59a26 100644
--- i/networkResponse/build.gradle.kts
+++ w/networkResponse/build.gradle.kts
@@ -26,7 +26,7 @@ tasks {
         reports {
             xml.isEnabled = true
             xml.destination = file("$buildDir/reports/jacoco/report.xml")
-            html.isEnabled = false
+            html.isEnabled = true
             csv.isEnabled = false
         }
     }
```

generates different report

<img width="1172" alt="1" src="https://user-images.githubusercontent.com/138671/78647088-5d224a80-78ba-11ea-9fc1-b5a48371d5f5.png">

where the lines 33, 36 and 39 are correctly marked as partially covered,
and which shows more details about the cause of partial coverage

<img width="1324" alt="2" src="https://user-images.githubusercontent.com/138671/78647105-61e6fe80-78ba-11ea-82e6-f7698cdacc6a.png">

**Closed by Godin** 2020-04-07 08:29 UTC
Labels: type: bug :bug:
