### ISSUE TITLE
partial branch coverage on first line of nested class

### ISSUE THREAD

**Issue by mirabilos** [jacoco/jacoco#1063] opened 2020-06-25 19:14 UTC
### Steps to reproduce

* JaCoCo version: jacoco-maven-plugin 0.8.5 (from right bottom corner of JaCoCo report) I don’t have a report, I read this in Sonar
* Operating system: Debian GNU/Linux
* Tool integration: Maven
* Complete executable reproducer: commit 7aff38324016f29557f1891afc044245ea66ad5a of `git clone https://evolvis.org/anonscm/git/useful-scripts/rfc822.git`
* Steps: build in Jenkins with Sonar integration

### Expected behaviour

There’s no incomplete branch coverage

### Actual behaviour

![Screenshot_20200625_211308](https://user-images.githubusercontent.com/861078/85784664-ca5eb280-b728-11ea-96aa-ec36979d43a8.png)

The line (249) in question is exactly:

    protected final class Substring {

This is a nested class of `src/main/java/org/evolvis/tartools/rfc822/Parser.java`.

**Comment by Godin** [comment] 2020-06-25 19:51
Class `Substring` contains `assert` and therefore the following branch in generated static initializer:

```
  static {};
    descriptor: ()V
    flags: (0x0008) ACC_STATIC
    Code:
      stack=1, locals=0, args_size=0
         0: ldc           #14                 // class org/evolvis/tartools/rfc822/Parser
         2: invokevirtual #15                 // Method java/lang/Class.desiredAssertionStatus:()Z
         5: ifne          12
         8: iconst_1
         9: goto          13
        12: iconst_0
        13: putstatic     #3                  // Field $assertionsDisabled:Z
        16: return
      LineNumberTable:
        line 249: 0
```

Closing as duplicate of #613

**Closed by Godin** 2020-06-25 19:51 UTC

**Comment by mirabilos** [comment] 2020-06-25 20:18
Evgeny Mandrikov dixit:

>Class `Substring` contains `assert` and therefore the following branch in generated static initializer:

Ah, okay; thank you for the detailled explanation.

>Closing as duplicate of #613 

Yes, I already saw that and documented it near those assert lines.

Thanks, and sorry for the noise,
//mirabilos
-- 
tarent solutions GmbH
Rochusstraße 2-4, D-53123 Bonn • http://www.tarent.de/
Tel: +49 228 54881-393 • Fax: +49 228 54881-235
HRB 5168 (AG Bonn) • USt-ID (VAT): DE122264941
Geschäftsführer: Dr. Stefan Barth, Kai Ebenrett, Boris Esser, Alexander Steeg
