### ISSUE TITLE
Code coverage not generated for Kotlin 1.5 and Jacoco 8.7 version 

### ISSUE THREAD

**Issue by gl-tester63** [jacoco/jacoco#1213] opened 2021-08-11 03:15 UTC
Code coverage not generated for Kotlin 1.5 and Jacoco 8.7 version 

### Steps to reproduce

* JaCoCo version:  0.8.7
* Complete executable reproducer: 
* Steps: 
*
In kotlin if you have code line internal f() {}
                                                               g()=f()

We will get below error.

### Expected behaviour
Should generate code coverage
### Actual behaviour
Getting error : java.lang.IllegalStateException:Unexpected SMAP line: *S KotlinDebug

Caused by: java.lang.IllegalStateException: Unexpected SMAP line: *S KotlinDebug
        at org.jacoco.core.internal.analysis.filter.KotlinInlineFilter.getFirstGeneratedLineNumber(KotlinInlineFilter.java:98)
        at org.jacoco.core.internal.analysis.filter.KotlinInlineFilter.filter(KotlinInlineFilter.java:43)
        at org.jacoco.core.internal.analysis.filter.Filters.filter(Filters.java:57)
        at org.jacoco.core.internal.analysis.ClassAnalyzer.addMethodCoverage(ClassAnalyzer.java:110)
        at org.jacoco.core.internal.analysis.ClassAnalyzer.access$100(ClassAnalyzer.java:31)
        at org.jacoco.core.internal.analysis.ClassAnalyzer$1.accept(ClassAnalyzer.java:99)
        at org.jacoco.core.internal.flow.ClassProbesAdapter$2.visitEnd(ClassProbesAdapter.java:89)
        at org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1279)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:679)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:391)
        at org.jacoco.core.analysis.Analyzer.analyzeClass(Analyzer.java:122)
        at org.jacoco.core.analysis.Analyzer.analyzeClass(Analyzer.java:138)
        ... 40 more

**Comment by Godin** [comment] 2021-08-11 06:39
Similarly to https://github.com/jacoco/jacoco/issues/1155#issuecomment-832642347

> JaCoCo version: 0.8.7

you can't have such stack trace when you really use JaCoCo 0.8.7

> at org.jacoco.core.internal.analysis.filter.KotlinInlineFilter.getFirstGeneratedLineNumber(KotlinInlineFilter.java:98)

because in 0.8.7 throw is not located on line 98, but on line 102:

https://github.com/jacoco/jacoco/blob/v0.8.7/org.jacoco.core/src/org/jacoco/core/internal/analysis/filter/KotlinInlineFilter.java#L102

So closing as duplicate of #1155

Please update your configuration to **really use JaCoCo version 0.8.7**

**Closed by Godin** 2021-08-11 06:39 UTC
Labels: type: bug :bug:

**Comment by naparam** [comment] 2021-08-11 08:11
@Godin after using  JaCoCo version 0.8.7 i am facing same issue 
ext {
        compose_version = '1.0.0'
        kotlin_version = '1.5.10'
    }

    **build.grdale** 
    
dependencies {
        classpath "com.android.tools.build:gradle:7.0.0"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath "org.jacoco:org.jacoco.core:0.8.7"

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }

**Jacoco Setup** in App Level build.gradle

acoco {
    toolVersion = '0.8.7'
}
task jacocoTestReport(type: JacocoReport,
        dependsOn: ['createDebugCoverageReport', 'testDebugUnitTest']) {
    group = "Reporting"
    description = "Generate Jacoco coverage reports for Debug build"

    reports {
        xml.enabled = true
        html.enabled = true
/      csv.enabled = true
    }
    def fileFilter = ['**/R.class',
                      '**/R$*.class',
                      '**/BuildConfig.*',
                      '**/Manifest*.*',
                      '**/*Test*.*',
                      'android/**/*.*',
                      '**/data/models/*',
                      '**/ComposeComponent**',
                      '**/DebugButtonComponent**',
                      '**/Color**',
                      '**/Shape**',
                      '**/abc**',
                      '**/Theme**',
                      '**/Type**',
                      '**/Wewes**',
    ]

    def debugTree = fileTree(
            // Java generated classes on Android project (debug build)
            dir: "$buildDir/intermediates/javac/debug",
            excludes: fileFilter
    ) + fileTree(
            // Kotlin generated classes on Android project (debug build)
            dir: "$buildDir/tmp/kotlin-classes/debug",
            excludes: fileFilter
    )

    def mainSrc = "${project.projectDir}/src/main/java"

    sourceDirectories.from = files([mainSrc])
    classDirectories.from = files([debugTree])
    additionalSourceDirs.from = files([
            "${buildDir}/generated/source/buildConfig/debug",
            "${buildDir}/generated/source/rs/debug"
    ])

    executionData.from = fileTree(dir: project.buildDir, includes: [
            'outputs/code_coverage/debugAndroidTest/connected/*coverage.ec', 'jacoco/testDebugUnitTest.exec'
    ])
}


tasks.withType(Test) {
    jacoco.includeNoLocationClasses = true
    jacoco.excludes = ['jdk.internal.*']
}
subprojects {
    configurations.all {
        resolutionStrategy {
            eachDependency { details ->
                if ('org.jacoco' == details.requested.group) {
                    details.useVersion "0.8.7"
                }
            }
        }
    }
}

**Comment by Godin** [comment] 2021-08-11 12:00
@naparam as already was said here in https://github.com/jacoco/jacoco/issues/1213#issuecomment-896543409
and as already was answered to you in https://github.com/jacoco/jacoco/issues/1214#issuecomment-896753543

please understand that 

> after using JaCoCo version 0.8.7

absolutely impossible to see

> ```
> Caused by: java.lang.IllegalStateException: Unexpected SMAP line: *S KotlinDebug
> at org.jacoco.core.internal.analysis.filter.KotlinInlineFilter.getFirstGeneratedLineNumber(KotlinInlineFilter.java:98)
> ```

because:

pay attention at
`at ... KotlinInlineFilter.java:98`
immediately after `Caused by: java.lang.IllegalStateException`
in your stacktrace

and

line `98` of `KotlinInlineFilter.java` in version `0.8.7` is a Java `break` statement and it can't throw `IllegalStateException`

https://github.com/jacoco/jacoco/blob/v0.8.7/org.jacoco.core/src/org/jacoco/core/internal/analysis/filter/KotlinInlineFilter.java#L98

Please update your configuration to really use JaCoCo version 0.8.7
