### ISSUE TITLE
I am also having same issue, Any resolution?

### ISSUE THREAD

**Issue by ManikantaTunikipati** [jacoco/jacoco#1635] opened 2024-06-12 11:28 UTC
Hi guys,

I'm curious, did anyone make it work with SonarQube?
I seem to have a clean JaCoCo report with the latest snapshot (`0.7.10-SNAPSHOT`) when I look at `./target/site/jacoco/index.html` report.
However the report in SonarQube is completely different: different code coverage (a lot less), different values for metrics like Complexity, Lines of code, etc...

Is it just me?
I even tried with the tiny example project provided by @Godin on the 2017-04-03 (I wrote one test method covering one stupid method doing a `System.out.println` for the sake of having one test) and then published in my SonarQube, and the results are massively different.

I created a small github project to ease reproduction of the issue: https://github.com/Sir4ur0n/example-jacoco-lombok-sonarqube

Here's the JaCoCo report:
![image](https://cloud.githubusercontent.com/assets/1204125/25271514/ac045692-2684-11e7-9a4d-0612bc3c3bd1.png)
![image](https://cloud.githubusercontent.com/assets/1204125/25271526/b56137a0-2684-11e7-9866-f1e4207c1680.png)
Here's the SonarQube report:
![image](https://cloud.githubusercontent.com/assets/1204125/25271543/c217961a-2684-11e7-9632-278a8f155f57.png)

Any help or pointer on what's wrong would be greatly appreciated :(

_Originally posted by @sir4ur0n in https://github.com/jacoco/jacoco/issues/513#issuecomment-296140333_

**Comment by Godin** [comment] 2024-07-13 21:25
Duplicate of #513

**Closed by Godin** 2024-07-13 21:25 UTC
