### ISSUE TITLE
Kotlin: Report shows incorrect number of lines

### ISSUE THREAD

**Issue by Skyliner1** [jacoco/jacoco#1190] opened 2021-05-20 23:19 UTC
### Steps to reproduce

* JaCoCo version:  0.8.5 (Also tried with JaCoCo 0.8.7 but it have the same behaviour)
* Kotlin version: 1.3.70
* Gradle version: 5.6.4
* Operating system: MacOS in local (Linux in Jenkins pipeline)
* Tool integration: Report generated with gradle.task
* Steps:

Hi guys, we use JaCoCo to generate an XML report of an multilang project (Java and Kotlin) that is uploaded later to SonarCloud.  Currently we have detected that the coverage information of some kotlin files is not uploaded due to the following error:
`Cannot import coverage information for file 'KotlinFile.kt', coverage data is invalid. Error: {}
java.lang.IllegalStateException: Line 15 is out of range in the file KotlinFile.kt `

We inspect the XML generated by jacoco and it shows an incorrect number of lines for that kotlin classes, as is shown below:
![image](https://user-images.githubusercontent.com/22103850/119058674-6d00cf00-b994-11eb-99b1-2caa7b693d0a.png)

The KotlinFile.kt have 14 lines of code:
![image](https://user-images.githubusercontent.com/22103850/119060095-2791d100-b997-11eb-9e2a-8e1aabe1321e.png)

For that Sonar detects more lines of code that there are in the file and the coverage is not taken for these classes. We have detected these behavior only in .kt files. Also we check the encoding of the file and it seems correct (UTF-8 / LF) 

These behavior seems similar to an old issue:
https://github.com/jacoco/jacoco/issues/763
https://community.sonarsource.com/t/sonar-kotlin-coverage-fails-due-to-line-is-out-of-range-errors/3201/15

Do you have any idea of that? We review the current issues but didnt find something similar.

### Expected behaviour
The report should show the same lines of code that the file (in the example, 14)

### Actual behaviour
The report should shows more lines of code only with some kotlin classes (with java there is no problem)

**Comment by Godin** [comment] 2021-05-21 06:46
Please provide **complete reproducer/example**, because screenshots are definitely not enough to reproduce your issue:

for `KotlinFile.kt`

```
package example;

enum class KotlinFile(val id: Int) { // line 3
  VALUEA(1), // line 4
  VALUEB(2); // line 5

  companion object {

    fun function(id: Int) = Unit // line 9
  }
}
```

execution of

```
kotlin-compiler-1.3.70/bin/kotlinc KotlinFile.kt -d classes
java -jar jacoco-0.8.7/lib/jacococli.jar report --classfiles classes --xml report.xml
```

produces `report.xml` with expected line numbers

```
        <sourcefile name="KotlinFile.kt">
            <line nr="3" mi="11" ci="0" mb="0" cb="0"/>
            <line nr="4" mi="11" ci="0" mb="0" cb="0"/>
            <line nr="5" mi="12" ci="0" mb="0" cb="0"/>
            <line nr="9" mi="1" ci="0" mb="0" cb="0"/>
            <counter type="INSTRUCTION" missed="44" covered="0"/>
            <counter type="LINE" missed="4" covered="0"/>
            <counter type="COMPLEXITY" missed="4" covered="0"/>
            <counter type="METHOD" missed="4" covered="0"/>
            <counter type="CLASS" missed="2" covered="0"/>
        </sourcefile>
```

Also please make sure that you really use JaCoCo version 0.8.7 by checking version in right bottom corner of HTML report generated by JaCoCo

<img width="1042" alt="Screenshot 2021-05-21 at 08 40 24" src="https://user-images.githubusercontent.com/138671/119093790-6dd74680-ba10-11eb-902d-418d100a494a.png">

**Comment by Godin** [comment] 2021-05-31 20:48
@Skyliner1 any chance that you will provide complete reproducer/example?
Otherwise we'll have to close this as unable to reproduce.

**Comment by Skyliner1** [comment] 2021-06-02 02:36
Hi @Godin, we started to make an test project in order to reproduce the issue. Making that test project we noticed that the version of JaCoCo used in the project build.gradle was not recognized by gradle, and in our CI-CD server the jacocoTestReport task was running with JaCoCo 0.7.9.

This issue seems to be a problem related to the Gradle version (5.6.4) according to this similar issue reported in the gradle github: https://github.com/gradle/gradle/issues/14033

To resolve this issue we have to force gradle to use the desired version of JaCoCo with the following block of code in the project build.gradle:

```
subprojects {
    configurations.all {
        resolutionStrategy {
            eachDependency { details ->
                if ('org.jacoco' == details.requested.group) {
                    details.useVersion "0.8.7"
                }
            }
        }
    }
}
```

I hope this helps for anyone with the same problem


Thanks for the help <3

**Comment by Skyliner1** [comment] 2021-06-02 02:37
Hi @Godin, we started to make an test project in order to reproduce the issue. Making that test project we noticed that the version of JaCoCo used in the project build.gradle was not recognized by gradle, and in our CI-CD server the jacocoTestReport task was running with JaCoCo 0.7.9.

This issue seems to be a problem related to the Gradle version (5.6.4) according to this similar issue reported in the gradle github: https://github.com/gradle/gradle/issues/14033

To resolve this issue we have to force gradle to use the desired version of JaCoCo with the following block of code in the project build.gradle:

```
subprojects {
    configurations.all {
        resolutionStrategy {
            eachDependency { details ->
                if ('org.jacoco' == details.requested.group) {
                    details.useVersion "0.8.7"
                }
            }
        }
    }
}
```

I hope this helps for anyone with the same problem


Thanks for the help <3

**Closed** 2021-06-02 03:44 UTC
Labels: declined: invalid :x:
