### ISSUE TITLE
Offline instrumentation for Android with launch crash

### ISSUE THREAD

**Issue by zyq940238856** [jacoco/jacoco#873] opened 2019-04-30 03:08 UTC
This is my log：
04-19 10:55:01.262  3666  3977 W OpenGLRenderer: Incorrectly called buildLayer on View: ShortcutAndWidgetContainer, destroying layer...
04-19 10:55:01.270  3822  3822 E JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 3805824)
04-19 10:55:01.271  3822  3822 W System.err: java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 3805824 bytes
04-19 10:55:01.272  3822  3822 W System.err:    at android.app.NotificationManager.notifyAsUser(NotificationManager.java:323)
04-19 10:55:01.272  3822  3822 W System.err:    at android.app.NotificationManager.notify(NotificationManager.java:289)
04-19 10:55:01.272  3822  3822 W System.err:    at android.app.NotificationManager.notify(NotificationManager.java:273)
04-19 10:55:01.272  3822  3822 W System.err:    at com.tencent.pangu.manager.notification.a.e.a(ProGuard:258)
04-19 10:55:01.273  3822  3822 W System.err:    at com.tencent.pangu.manager.notification.af.handleMessage(ProGuard:89)
04-19 10:55:01.273  3822  3822 W System.err:    at android.os.Handler.dispatchMessage(Handler.java:102)
04-19 10:55:01.273  3822  3822 W System.err:    at android.os.Looper.loop(Looper.java:164)
04-19 10:55:01.273  3822  3822 W System.err:    at android.app.ActivityThread.main(ActivityThread.java:6494)
04-19 10:55:01.273  3822  3822 W System.err:    at java.lang.reflect.Method.invoke(Native Method)
04-19 10:55:01.273  3822  3822 W System.err:    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
04-19 10:55:01.273  3822  3822 W System.err:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
04-19 10:55:01.273  3822  3822 W System.err: Caused by: android.os.TransactionTooLargeException: data parcel size 3805824 bytes
04-19 10:55:01.273  3822  3822 W System.err:    at android.os.BinderProxy.transactNative(Native Method)
04-19 10:55:01.273  3822  3822 W System.err:    at android.os.BinderProxy.transact(Binder.java:764)
04-19 10:55:01.273  3822  3822 W System.err:    at android.app.INotificationManager$Stub$Proxy.enqueueNotificationWithTag(INotificationManager.java:1385)
04-19 10:55:01.273  3822  3822 W System.err:    at android.app.NotificationManager.notifyAsUser(NotificationManager.java:320)
04-19 10:55:01.273  3822  3822 W System.err:    ... 10 more
04-19 10:55:05.173 19880 19880 W MemoryCheckThre: type=1400 audit(0.0:25081): avc: denied { read } for name="mem" dev="debugfs" ino=3335472 scontext=u:r:untrusted_app_25:s0:c512,c768 tcontext=u:object_r:debugfs:s0 tclass=file permissive=0

**Comment by Godin** [comment] 2019-04-30 09:11
Closing due to absence of steps to reproduce.
Moreover integration with Android is not developed by us, but by developers of Android SDK - https://source.android.com/setup/contribute/report-bugs

**Closed by Godin** 2019-04-30 09:11 UTC
