### ISSUE TITLE
Filtering: Kotlin interface default implementations

### ISSUE THREAD

**Issue by sellmair** [jacoco/jacoco#978] opened 2019-11-25 15:07 UTC
### Scenario

* JaCoCo version: 0.8.5
* Operating system: MacOS
* Tool integration: Gradle, Kotlin

### Current Behaviour
Kotlin Interface default implementations like 
```kotlin
interface SomeInterface {
    fun someFunction() = // Default implementation
}
```

Will lead to JaCoCo reporting uncovered functions for implementations of those interfaces:

```kotlin
class SomeImplementation: SomeInterface {

}
```

This is because of the Kotlin compiler effectively adding the default implementation to the compiled class like

```java

public class SomeImplementation implements SomeInterface {
    
    public void someFunction() {
        DefaultImpls.someFunction(this)
    } 

}

```

### Wanted Behaviour
I would like to have those default implementations ignored from JaCoCo. To cover those, it should be fine just to cover the default implementation once.

**Comment by sellmair** [comment] 2019-11-25 17:02
This should maybe be solved by the Kotlin compiler itself? It might make sense to annotate those generated methods with some kind of `@Generated ` annotation.

**Comment by Godin** [comment] 2019-11-29 00:54
> This should maybe be solved by the Kotlin compiler itself?

I'm closing this ticket as duplicate of #905, which indeed suggests to make a change in compiler to not produce line number for generated delegating methods (CC @goodwinnk).

 So @sellmair could you please report this to developers of Kotlin compiler in [their issue tracker](https://youtrack.jetbrains.com/issues/KT) with cross-reference to/from this ticket?

**Closed by Godin** 2019-11-29 00:54 UTC
Labels: type: enhancement
