### ISSUE TITLE
java.io.EOFException: Unexpected end of ZLIB input stream

### ISSUE THREAD

**Issue by bartlomiej-gora** [jacoco/jacoco#398] opened 2016-04-16 19:44 UTC
Hi I have problem with my Jenkins, running Jacoco.

### Steps to reproduce
We have created Configuration to use jacoco test coverage in Jenkins.

JaCoCo version: 0.7.6
```
    Operating system: Linux version 3.2.0-56-generic (buildd@roseapple) (gcc version 4.6.3 (Ubuntu/Linaro 4.6.3-1ubuntu5) ) #86-Ubuntu SMP Wed Oct 23 09:20:45 UTC 2013

Tool integration:Ant/Jenkins

Jenkins ver. 1.652
```

### Expected behaviour
Jenkins Test job should return with success.

### Actual behaviour
I'm Getting this error:
```
ERROR: Step ‘Record JaCoCo coverage report’ aborted due to exception: 
java.io.EOFException: Unexpected end of ZLIB input stream
	at java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:240)
	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
	at java.util.zip.ZipInputStream.read(ZipInputStream.java:194)
	at java.util.zip.ZipInputStream.closeEntry(ZipInputStream.java:140)
	at java.util.zip.ZipInputStream.getNextEntry(ZipInputStream.java:118)
	at org.jacoco.core.analysis.Analyzer.analyzeZip(Analyzer.java:245)
	at org.jacoco.core.analysis.Analyzer.analyzeAll(Analyzer.java:178)
	at org.jacoco.core.analysis.Analyzer.analyzeAll(Analyzer.java:208)
	at hudson.plugins.jacoco.ExecutionFileLoader.analyzeStructure(ExecutionFileLoader.java:126)
	at hudson.plugins.jacoco.ExecutionFileLoader.loadBundleCoverage(ExecutionFileLoader.java:133)
	at hudson.plugins.jacoco.JacocoReportDir.parse(JacocoReportDir.java:102)
	at hudson.plugins.jacoco.JacocoBuildAction.loadRatios(JacocoBuildAction.java:322)
	at hudson.plugins.jacoco.JacocoBuildAction.load(JacocoBuildAction.java:304)
	at hudson.plugins.jacoco.JacocoPublisher.perform(JacocoPublisher.java:371)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:782)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:723)
	at hudson.model.Build$BuildExecution.post2(Build.java:185)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:668)
	at hudson.model.Run.execute(Run.java:1763)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:410)
```

**Comment by Godin** [comment] 2016-04-16 21:40
@bartlomiej-gora Jenkins plugin is not developed by us, please contact maintainers of this plugin.

**Comment by bartlomiej-gora** [comment] 2016-04-17 09:50
@Godin Hi. Thank you for reply.
I've noticed, that the exception war thrown at org.jacoco.core.analysis, that's why I placed it here, but I will report it to the plugin project. 

Thank you.

**Comment by bartlomiej-gora** [comment] 2016-04-17 10:22
@Godin Could you please check one more time? The stacktrace points that  org.jacoco.core.analysis.Analyzer.analyzeZip(Analyzer.java:245) throws that error.
I think That the problem is with the ZipInputstrem constructor there.
    final ZipInputStream zip = new ZipInputStream(input);

It might be connected with this jdk bug:
http://bugs.java.com/bugdatabase/view_bug.do?bug_id=4040920

Sorry for comment, but Github don't allow messaging.

**Comment by Godin** [comment] 2016-04-17 10:54
@bartlomiej-gora 

1. Stack trace doesn't correspond to specified JaCoCo version - entry `org.jacoco.core.analysis.Analyzer.analyzeAll(Analyzer.java:208` is `} else {` in 0.7.6 version and obviously can't be part of stack trace - https://github.com/jacoco/jacoco/blob/v0.7.6/org.jacoco.core/src/org/jacoco/core/analysis/Analyzer.java#L208 , hence attempt to map the rest of stack trace on 0.7.6 version is not reliable.
2. The remaining part of stack trace is definitely Jenkins Plugin (`hudson.plugins.jacoco`), which is not developed by us.
3. Mentioned JDK bug is marked as fixed a long time ago.

We'll be happy to investigate, if you able to provide reproducer, which doesn't involve Jenkins stack.

Thanks for your understanding.

**Comment by marchof** [comment] 2016-04-17 11:03
@Godin @bartlomiej-gora The most likely explanation is that the zip file is actually corrupted. Also this seems to be a very old version of JaCoCo. Since 0.6.3 the error message contains the location of the problematic file.
To investigate we would need the ZIP/JAR file causing the problem.

**Comment by Godin** [comment] 2016-04-17 11:09
@marchof good point about 0.6.3, but seems that we are not catching all exceptions in `analyzeZip`, i.e. if `zip.getNextEntry()` throws an `IOException`, then location won't be presented in stacktrace - https://github.com/jacoco/jacoco/blob/v0.7.6/org.jacoco.core/src/org/jacoco/core/analysis/Analyzer.java#L248

**Comment by marchof** [comment] 2016-04-17 11:13
@Godin You're right: We only add context information when our own processing fails. All regular IOExceptions from reading the underlying sources we simply pass on. So this would be a separate enhancement request, but I see no priority for this.

**Comment by bartlomiej-gora** [comment] 2016-04-17 18:28
Hi @Godin , @marchof  first of all, I want to thank you for your support. I think your are right. The stacktrace is not from the latest version of the library. I have checked the Jenkins plugin repository, and found this:
https://github.com/jenkinsci/jacoco-plugin/blob/master/pom.xml#L94
So the plugin itself uses 0.7.5.
I'm runnig the 0.7.6 in my ant task first, and then,in the next step Jenkins uses the Jacoco plugin.
So I will downgrade my ant script to use 0.7.6 so it will be compatibile with the plugin. Maybe that will help.

Thank you for your help.

**Comment by Godin** [comment] 2016-04-17 19:27
@marchof I created #400 to not forget this.

**Comment by Godin** [comment] 2016-04-17 19:32
@bartlomiej-gora I have doubts that version mismatch plays role here, most likely @marchof is right and indeed there is corrupted zip.  Feel free to report if you'll manage to find root cause of the issue or not, and meanwhile I'm closing this ticket.

**Closed by Godin** 2016-04-17 19:32 UTC
Labels: invalid, otherproject
