### ISSUE TITLE
"viewModelScope.launch" block partially covered for Kotlin 

### ISSUE THREAD

**Issue by victorsegurapedidosya** [jacoco/jacoco#1420] opened 2023-03-30 20:15 UTC
### Steps to reproduce

* JaCoCo version:  0.8.7.202105040129
* Operating system: macOS
* Steps: I'm using 1.7.20 kotlin version and 0.8.7.202105040129 version of Jacoco. Just run jacocoTestReport task to build a html report to check coverage.

### Expected behaviour
 It should be covered at 100%
### Actual behaviour
 It doesn't. like the image:
![Screen Shot 2023-03-30 at 15 03 16](https://user-images.githubusercontent.com/89480657/228953225-6ad52d9d-a97c-459c-ac60-0036808f393b.png)

**Comment by Godin** [comment] 2023-03-31 07:40
Duplicate of https://github.com/jacoco/jacoco/pull/1283

**Closed by Godin** 2023-03-31 07:40 UTC
Labels: type: bug :bug:
