### ISSUE TITLE
Kotlin 1.5 InlineFilter error

### ISSUE THREAD

**Issue by mattinger** [jacoco/jacoco#1209] opened 2021-07-09 00:13 UTC
### Steps to reproduce

Create an android project and create the following class (honest, i presume you can just create an arbitrary class in any kind of project) with this content.

```
class SampleFragment: Fragment() {
    inline fun f() {}
    fun g() = f()
}
```

Create the Jacoco Test Report

* JaCoCo version:  0.8.7
* Operating system: Macos 11.2.3
* Tool integration: Gradle 4.0.1
* Complete executable reproducer:
* Steps:

### Expected behaviour

Tests are run and report produced

### Actual behaviour

Exception is thrown

Caused by: java.lang.IllegalStateException: Unexpected SMAP line: *S KotlinDebug
        at org.jacoco.core.internal.analysis.filter.KotlinInlineFilter.getFirstGeneratedLineNumber(KotlinInlineFilter.java:98)
        at org.jacoco.core.internal.analysis.filter.KotlinInlineFilter.filter(KotlinInlineFilter.java:44)
        at org.jacoco.core.internal.analysis.filter.Filters.filter(Filters.java:58)
        at org.jacoco.core.internal.analysis.ClassAnalyzer.addMethodCoverage(ClassAnalyzer.java:119)

This seems to be a general problem with inlined functions, as i have seen other instances where higher order functions that are passed inline functions as arguments produce the same type of issue.

**Comment by marchof** [comment] 2021-07-09 05:09
Thanks @mattinger for reporting this! Can you please provide a minimal executable reproducer? Preferrably a GitHub repo so we can debug this?

If this is not possible we need at least the the following:

* Exact version of Kotlin compiler used
* The class file that causes the problem

Thx!

**Comment by Godin** [comment] 2021-07-09 06:57
Similarly to https://github.com/jacoco/jacoco/issues/1155#issuecomment-832642347

> JaCoCo version: 0.8.7

you can't have such stack trace when you really use JaCoCo 0.8.7

> at org.jacoco.core.internal.analysis.filter.KotlinInlineFilter.getFirstGeneratedLineNumber(KotlinInlineFilter.java:98)

because in 0.8.7 throw is not located on line 98, but on line 102:

https://github.com/jacoco/jacoco/blob/v0.8.7/org.jacoco.core/src/org/jacoco/core/internal/analysis/filter/KotlinInlineFilter.java#L102

So closing as duplicate of #1155

Please update your configuration to **really use JaCoCo version 0.8.7**

**Closed by Godin** 2021-07-09 06:57 UTC
Labels: feedback pending, type: bug :bug:
