### ISSUE TITLE
getEnclosingClass() and getDeclaringClass() return null [reflection]

### ISSUE THREAD

**Issue by jvanheesch** [jacoco/jacoco#584] opened 2017-08-30 14:09 UTC
This is an issue tracker. Please use our mailing list for general questions: 
https://groups.google.com/forum/?fromgroups=#!forum/jacoco

Also check FAQ before opening an issue: http://www.jacoco.org/jacoco/trunk/doc/faq.html

### Steps to reproduce
quickstart example:
[quickstart.tar.gz](https://github.com/jacoco/jacoco/files/1264268/quickstart.tar.gz)

Run (`mvn test`) the quickstart example.
JaCoCo version: 0.7.9
Operating system:
Tool integration: Maven

### Expected behaviour
`SampleTest` doesn't fail - `getEnclosingClass()` and `getDeclaringClass()` return `SomeClass.class`.

### Actual behaviour
When running the test with Maven and JaCoCo (`mvn test`), the test fails.
If the JaCoCo plugin is removed, `mvn test` will successfully run the test.

**Comment by Godin** [comment] 2017-08-30 21:37
@jvanheesch  first of all - thank you for this report with a complete concise reproducer! :thumbsup:

In presence of Serializable lambdas javac will generate [method `$deserializeLambda$`](https://docs.oracle.com/javase/8/docs/api/java/lang/invoke/SerializedLambda.html). This method is big in given example due to amount of lambdas. So that JaCoCo instrumentation adds wide jumps into this method. They are handled in a specific way by ASM library that we use. And seems that ASM looses `InnerClasses` attribute during this process - https://gitlab.ow2.org/asm/asm/blob/ASM_5_2/src/org/objectweb/asm/ClassWriter.java#L991-1006

Workarounds:
* reduce size of a method by reducing number of lambdas - as far as I can see for given example will be enough by 1
* exclude class from instrumentation

Should be noted that we tend to not implement any exclusions of methods during instrumentation for various reasons. One of them - such changes break compatibility of exec-file. And better to get fix in ASM. So will try to craft reproducer without JaCoCo and report this to ASM developers.

**Comment by Godin** [comment] 2017-09-06 19:12
Created bug report in ASM library:
http://forge.ow2.org/tracker/?func=detail&aid=317792&group_id=23&atid=100023

**Comment by jvanheesch** [comment] 2017-09-06 19:28
@Godin Thank you very much, both for the quick response and the ASM reproducer!
I will definitely keep an eye on that ticket.

**Comment by Godin** [comment] 2017-10-19 21:51
Fixed by #600

**Closed by Godin** 2017-10-19 21:51 UTC
Labels: component: core, type: bug
