### ISSUE TITLE
Display global coverage in maven console output

### ISSUE THREAD

**Issue by jripault** [jacoco/jacoco#569] opened 2017-07-19 19:48 UTC
Hi,
I use Gitlab for my build and it has a feature to extract the coverage from the output of the build. Jacoco Maven plugin does not write this info in stdout of maven console stdout. Is there an easy way to do that, like in the report mojo ? 

Thanks

JaCoCo version: 0.7.9
Operating system: Ubuntu
Tool integration: Maven

**Comment by Godin** [comment] 2017-07-19 22:32
Duplicate of #488

**Closed by Godin** 2017-07-19 22:32 UTC

**Comment by McNetic** [comment] 2017-09-21 14:33
Why is this a duplicate of #488? This is about the maven console output. Currently, for failed coverage checks, there is an output like this:
`[WARNING] Rule violated for bundle ensupply-web: instructions covered ratio is 0.51, but expected minimum is 0.52`
Whereas for successful coverage checks, there is only an output of:
`[INFO] All coverage checks have been met.`

It would not hurt but in fact be very nice to (at least optionally) have a short summary for failed as well as successful builds of all configured thresholds and the respective results. Something like this:
```
[INFO] JaCoCo coverage thresholds:
[INFO] Class: min=0, max=0, result=74
[INFO] Method: min=0, max=0, result=63
[INFO] Line: min=0, max=0, result=54
[INFO] Branch: min=0, max=0, result=49
[INFO] Instruction: min=0, max=50, result=52
[INFO] Complexity: min=0, max=50, result=54
[success or error message as above]
```
So you can easily see in the build output where the coverage thresholds are currently met.

Would you accept a pull request implementing this?

**Comment by marchof** [comment] 2017-09-21 14:50
@McNetic Thanks for your comment! Unfortunatelly it is not as easy as you describe it: JaCoCo coverage checks can be configured on any element (class, package) not just globally (bundle). So you might have thousands of lines output.

We already have a pull request pending for this: #237

**Comment by Godin** [comment] 2017-09-21 15:13
@McNetic 

> Why is this a duplicate of #488?

Because without yours comment they both are about GitLab ;)
