### ISSUE TITLE
includes/excludes does not work in maven command line

### ISSUE THREAD

**Issue by DreamL** [jacoco/jacoco#687] opened 2018-05-29 03:27 UTC
includes/excludes does not work in maven command line, not support or my bug?

I tried 

`mvn org.jacoco:jacoco-maven-plugin:report 
-Dexcludes=com_ht_es_service/ElasticSearchServiceImpl.class`

and

``mvn org.jacoco:jacoco-maven-plugin:report -Dexcludes=com_ht_es_service.ElasticSearchServiceImpl``

Always analyze and report all the class coverage, is that not supported or I did something wrong?

By the way, I have the same problem on the goal:jacoco-maven-plugin:prepare-agent when I generate the exec file.

thanks!

**Comment by Godin** [comment] 2018-05-29 07:10
As you can see from documentation (https://www.jacoco.org/jacoco/trunk/doc/report-mojo.html and https://www.jacoco.org/jacoco/trunk/doc/prepare-agent-mojo.html) there is no property to specify includes and excludes from command-line.

**Comment by Godin** [comment] 2018-05-29 07:10
Duplicate of #577

**Closed** 2018-05-29 07:11 UTC
Labels: declined: duplicate

**Comment by DreamL** [comment] 2018-05-29 08:04
thank you
