### ISSUE TITLE
Fix SonarQube Link

### ISSUE THREAD

**Issue by marchof** [jacoco/jacoco#693] opened 2018-06-12 11:25 UTC
Our documentation points to the old sonarqube instance in `environment.html`.

The new link is https://sonarcloud.io/dashboard?id=org.jacoco%3Aorg.jacoco.build

**Comment by Godin** [comment] 2018-06-13 00:18
@marchof isn't it a duplicate of #616 ? or at least #616 is wider - it is not only about broken link, but also about currently disabled analysis.

**Closed** 2018-06-13 05:22 UTC
Labels: component: documentation, declined: duplicate
