### ISSUE TITLE
FR: Gitlab coverage report

### ISSUE THREAD

**Issue by enexusde** [jacoco/jacoco#623] opened 2017-11-20 11:55 UTC
As described in https://medium.com/@kaiwinter/javafx-and-code-coverage-on-gitlab-ci-29c690e03fd6
The percentage of coverage can only be reported to gitlab by print the report to the console.

### Steps to reproduce

JaCoCo version: Latest
Operating system: All
Tool integration: Maven, Gitlab, Github

### Expected behaviour

Parse build-out 

### Actual behaviour

Print report to build-out and parse build-out.

**Comment by Godin** [comment] 2017-11-20 12:02
Duplicate of #488

**Closed by Godin** 2017-11-20 12:02 UTC

**Comment by enexusde** [comment] 2017-11-20 16:58
I disagree. The coverage is the result of a test-report! All test results in maven are outputed to the console.

**Comment by Godin** [comment] 2017-11-20 18:34
@enexusde as of today to our taste and compared with other tasks, addition of printing of coverage percentage in console raises far more questions (one for example in case of GitLab is multi-module projects) with all the consequences than benefits. Especially that such information already can be easily extracted from reports, which are btw far more actionable than plain total value, and also since the use case (as it is described) is quite specific to GitLab.

Thank you for your understanding.
