### ISSUE TITLE
Jacoco cant do coverage inside coroutines block

### ISSUE THREAD

**Issue by yehezkiell** [jacoco/jacoco#1045] opened 2020-04-13 12:38 UTC
### Steps to reproduce

* JaCoCo version:  0.8.3
* Operating system: Mac Os
* Tool integration: Gradle

### Expected behaviour
All reports turn into green or if not just go with color

### Actual behaviour
It doesnt has any color at all, I've test it and everything going through this code

<img width="1038" alt="Screen Shot 2020-04-13 at 18 47 40" src="https://user-images.githubusercontent.com/17094969/79120876-2c607a80-7dbe-11ea-8bc8-f52fb4262277.png">

**Comment by marchof** [comment] 2020-04-13 21:03
Please provide a fully executable reproducer (Guthub repo), otherwise we cannot debug this.

**Comment by Godin** [comment] 2020-04-13 21:27
Closing due to absence of required **complete reproducer**

<img width="589" alt="required" src="https://user-images.githubusercontent.com/138671/79161635-19f53980-7ddc-11ea-8148-2f1479cb6108.png">

Furthermore, not even counting that JaCoCo version 0.8.3 is not the latest release, for the following `Example.kt`

```
import kotlinx.coroutines.*

fun main(args: Array<String>) {
    GlobalScope.launch {
        println("Hello")
    }
    Thread.sleep(2000) // wait for 2 seconds
    println("Stop")
}
```

execution of

```
kotlin-1.3.61/bin/kotlinc \
    -cp kotlin-1.3.61/lib/kotlinx-coroutines-core-1.0.1.jar \
    -d classes \
    Example.kt

java \
    -javaagent:jacoco-0.8.3/lib/jacocoagent.jar \
    -cp kotlin-1.3.61/lib/kotlin-stdlib.jar:kotlin-1.3.61/lib/kotlinx-coroutines-core-1.0.1.jar:classes \
    ExampleKt

java \
    -jar jacoco-0.8.3/lib/jacococli.jar \
    report jacoco.exec \
    --classfiles classes \
    --html report \
    --sourcefiles .
```

generates

<img width="765" alt="report" src="https://user-images.githubusercontent.com/138671/79161916-9a1b9f00-7ddc-11ea-8268-c61bb933ba3b.png">

So in the absence of complete reproducer, one can only make a wild guess that you probably configured exclusions and excluded from the analysis class files containing coroutines (such as `ExampleKt$main$1.class` for the above example).

**Closed by Godin** 2020-04-13 21:27 UTC
Labels: feedback pending, type: bug :bug:
