### ISSUE TITLE
JaCoCo agent Configuration in Weblogic | ClassCastException in server startup

### ISSUE THREAD

**Issue by ashishbha** [jacoco/jacoco#567] opened 2017-07-14 12:45 UTC
Web logic Startup parameter 

-XXaggressive -Xmx8192m -Xms8192m -Xgc:pausetime -Xgc:gencon -XXnosystemgc -Duser.home=/scratch/app/product/fmw/XXXinstall/XXX/config -Dsun.net.client.defaultConnectTimeout=10000 
 -javaagent:/scratch/app/product/fmw/user_projects/domains/host_domain/lib/jacocoagent.jar=destfile=/scratch/app/product/fmw/user_projects/domains/host_domain/tmp/host_jacoco.exec,output=tcpserver,address=,includes=com.*

Issue :

Weblogic Server is not getting started...and in logs facing 

Caused By: java.lang.ClassCastException: [Z

Please suggest if any other Parameter needs to pass ..

**Comment by Godin** [comment] 2017-07-14 13:46
What are the **exact steps** to reproduce your issue? How full exception stack trace looks like? Which version of JaCoCo you use? Which version of WebLogic Server you use? Where we can download it? Which small application we can run on it to reproduce your issue?

In absence of reproducer we can only recommend to do a search of a similar problem in internet.

Such search might reveal following as a possible explanation of your problem: To collect execution data JaCoCo adds members to the classes. One of those members is a field with type `boolean[]` (`[Z` in bytecode notation). These members are [marked as `synthetic`](https://docs.oracle.com/javase/7/docs/api/java/lang/reflect/Member.html#isSynthetic()). Your application and its libraries must ignore `synthetic` members. If they are not ignored, then change you application to do so, or exclude classes from instrumentation using agent parameters `includes` and `excludes`. Full stack trace is a possible way to determine problematic libraries and classes.

**Comment by ashishbha** [comment] 2017-07-15 06:14
Hi Godin- Thanks for reply.

**Steps to reproduc**e ; when I am trying to load JaCoCo after giving above mention parameter and restating the web-logic managed server ..server is not coming UP.  

I have downloaded lib from : http://search.maven.org/remotecontent?filepath=org/jacoco/jacoco/0.7.9/jacoco-0.7.9.zip

We are using **Weblogic version 11g** and **java version 1.6** 

Full stack trace ..

<Jul 14, 2017 6:08:22 PM GMT+05:30> <Error> <Deployer> <BEA-149231> <Unable to set the activation state to true for the application 'obp-host'.
weblogic.application.ModuleException: [HTTP:101216]Servlet: "bootstrap" failed to preload on startup in Web application: "XXX.channel.branch".
java.lang.RuntimeException: XXX.infra.exception.FatalException: Could not find Error Message for  [FC_SM_10411]  , Please add it in ErrorMessages resource bundle !!!!!
        at XXX.channel.branch.bootstrap.BootstrapServlet.init(BootstrapServlet.java:59)
        at javax.servlet.GenericServlet.init(GenericServlet.java:241)
        at weblogic.servlet.internal.StubSecurityHelper$ServletInitAction.run(StubSecurityHelper.java:283)
        at weblogic.security.acl.internal.AuthenticatedSubject.doAs(AuthenticatedSubject.java:321)
        at weblogic.security.service.SecurityManager.runAs(SecurityManager.java:120)
		Caused by: XXX.infra.exception.FatalException: Could not find Error Message for  [FC_SM_10411]  , Please add it in ErrorMessages resource bundle !!!!!
        at XXX.infra.error.ErrorManager.throwFatalException(ErrorManager.java:402)
        at XXX.app.bootstrap.BootstrapInitializer.initializeSecuritySingletons(BootstrapInitializer.java:295)
        at XXX.channel.branch.bootstrap.BootstrapServlet.init(BootstrapServlet.java:46)
        ... 42 more
Caused by: XXX.infra.exception.FatalException: Errors occurred while loading accessible resources.
        at XXX.infra.error.ErrorManager.throwFatalException(ErrorManager.java:402)
        at XXX.app.sms.service.provider.AccessibleResourceLoader.loadResources(AccessibleResourceLoader.java:235)
        at XXX.app.adapter.impl.sms.AccessibleResourceLoaderAdapter.loadResources(AccessibleResourceLoaderAdapter.java:49)
        at XXX.app.bootstrap.BootstrapInitializer.initializeSecuritySingletons(BootstrapInitializer.java:292)
        ... 43 more
Caused by: XXX.framework.exception.BusinessException: Errors occurred while loading accessible resources.
        at XXX.app.sms.service.provider.AccessibleResourceLoader.initializeSingleton(AccessibleResourceLoader.java:193)
        at XXX.app.sms.service.provider.AccessibleResourceLoader.loadResources(AccessibleResourceLoader.java:232)
        ... 45 more
**Caused by: java.lang.ClassCastException: [Z**
        at XXX.app.AbstractApplication.fetchAllOverriddenServices(AbstractApplication.java:1000)
        at XXX.app.AbstractApplication.checkAccess(AbstractApplication.java:930)
        at XXX.app.sms.service.provider.AccessibleResourceApplicationService.initializeRequestedResource(AccessibleResourceApplicationService.java:1011)
        at XXX.app.sms.service.provider.AccessibleResourceLoader.initializeSingleton(AccessibleResourceLoader.java:187)
        at XXX.app.sms.service.provider.AccessibleResourceLoader.loadResources(AccessibleResourceLoader.java:232)
        at XXX.app.adapter.impl.sms.AccessibleResourceLoaderAdapter.loadResources(AccessibleResourceLoaderAdapter.java:49)
        at XXX.app.bootstrap.BootstrapInitializer.initializeSecuritySingletons(BootstrapInitializer.java:292)
        at XXX.channel.branch.bootstrap.BootstrapServlet.init(BootstrapServlet.java:46)


**Note ; Please let me know which synthetic class need to excludes..while restarting weblogic 11g.** 

**Note2 after removing below mention Parameter  server is coming up and application is working fine.**

**-javaagent:/scratch/app/product/fmw/user_projects/domains/host_domain/lib/jacocoagent.jar=destfile=/scratch/app/product/fmw/user_projects/domains/host_domain/tmp/host_jacoco.exec,output=tcpserver,address=,includes=com.***

**Comment by ashishbha** [comment] 2017-07-15 06:57
![image](https://user-images.githubusercontent.com/30177623/28237260-f037ba9a-6958-11e7-8311-46b87592e837.png)

**Comment by Godin** [comment] 2017-07-18 01:36
WebLogic server without applications starts perfectly with JaCoCo.

So please understand that we can't tell you why your code or your library is trying to do a wrong cast. And hence can't tell which class needs to be excluded exactly because this is your code to which we don't have any access.

Run your application under debugger, put a breakpoint at line `XXX.app.AbstractApplication.fetchAllOverriddenServices(AbstractApplication.java:1000)` and investigate why there is wrong cast and which classes to exclude.
Or start excluding packages of your application one by one.

Furthermore since WebLogic is a commercial product, while JaCoCo is fully open-source and free, please consider requesting consultancy/support from the vendor - Oracle.

Thank you for your understanding.

**Closed by Godin** 2017-07-18 01:36 UTC
Labels: feedback pending
