### ISSUE TITLE
Incorrect Branching On Return Statement

### ISSUE THREAD

**Issue by cro-magnon** [jacoco/jacoco#1292] opened 2022-03-04 18:32 UTC
THIS IS A BUG TRACKER ONLY. FOR QUESTIONS PLEASE CHECK FAQ OR USE FORUM:

http://www.jacoco.org/jacoco/trunk/doc/faq.html

https://groups.google.com/forum/?fromgroups=#!forum/jacoco

Please understand that
ISSUES WITHOUT FOLLOWING INFORMATION WILL BE CLOSED WITHOUT COMMENTS!
Thank you for filling bug report!

### Steps to reproduce

* JaCoCo version:  0.8.7
* Operating system: OSX
* Tool integration: Gradle
* Example project: https://github.com/cro-magnon/jacoco-bug

* Steps: (what exactly are you doing with the above reproducer?)
Just run a `./gradlew clean build`
Navigate to the coverage report file as described in the README.

### Expected behaviour
It is a return statement, it should be covered.
There should be no missing branches whatsoever.

### Actual behaviour
<img width="561" alt="branch_coverage_bug" src="https://user-images.githubusercontent.com/53350954/156821210-12d9d4ba-5932-48c9-914f-d8176cd3ff4f.png">

**Comment by cro-magnon** [comment] 2022-03-04 20:22
Not sure if it's helpful or not, but this same code will pass if the kotlin version is set to 1.5.20. Haven't really tried out any other version. So I don't know if it's some different way the compiled classes are getting generated that makes jacoco see things differently.

**Comment by Godin** [comment] 2022-03-05 09:59
Duplicate of #1266

**Closed by Godin** 2022-03-05 09:59 UTC
Labels: type: bug :bug:
